import { math } from '../../../core/math/math.js';
import { Color } from '../../../core/math/color.js';
import { Vec4 } from '../../../core/math/vec4.js';
import { LIGHTSHAPE_PUNCTUAL, LIGHTFALLOFF_LINEAR, SHADOW_PCF3, BLUR_GAUSSIAN, SHADOWUPDATE_REALTIME, MASK_AFFECT_DYNAMIC, MASK_AFFECT_LIGHTMAPPED, MASK_BAKE, LAYERID_WORLD } from '../../../scene/constants.js';
import { Asset } from '../../asset/asset.js';
import { Component } from '../component.js';

const _lightProps = [];
const _lightPropsDefault = [];

/**
 * The Light Component enables the Entity to light the scene. There are three types of light:
 * directional, omni and spot. Directional lights are global in that they are considered to be
 * infinitely far away and light the entire scene. Omni and spot lights are local in that they have
 * a position and a range. A spot light is a specialization of an omni light where light is emitted
 * in a cone rather than in all directions. Lights also have the ability to cast shadows to add
 * realism to your scenes.
 *
 * ```javascript
 * // Add a pc.LightComponent to an entity
 * const entity = new pc.Entity();
 * entity.addComponent('light', {
 *     type: "omni",
 *     color: new pc.Color(1, 0, 0),
 *     range: 10
 * });
 *
 * // Get the pc.LightComponent on an entity
 * const lightComponent = entity.light;
 *
 * // Update a property on a light component
 * entity.light.range = 20;
 * ```
 *
 * @property {string} type The type of light. Can be:
 *
 * - "directional": A light that is infinitely far away and lights the entire scene from one
 * direction.
 * - "omni": An omni-directional light that illuminates in all directions from the light source.
 * - "spot": An omni-directional light but is bounded by a cone.
 *
 * Defaults to "directional".
 * @property {Color} color The Color of the light. The alpha component of the color is ignored.
 * Defaults to white (1, 1, 1).
 * @property {number} intensity The brightness of the light. Defaults to 1.
 * @property {number} luminance The physically based luminance. Only used if scene.physicalUnits is true. Defaults to 0.
 * @property {number} shape The light source shape. Can be:
 *
 * - {@link LIGHTSHAPE_PUNCTUAL}: Infinitesimally small point.
 * - {@link LIGHTSHAPE_RECT}: Rectangle shape.
 * - {@link LIGHTSHAPE_DISK}: Disk shape.
 * - {@link LIGHTSHAPE_SPHERE}: Sphere shape.
 *
 * Defaults to pc.LIGHTSHAPE_PUNCTUAL.
 * @property {boolean} affectSpecularity If enabled, material specularity will be affected by this light.
 * Ignored for lights other than {@link LIGHTTYPE_DIRECTIONAL}. Defaults to true.
 * @property {boolean} castShadows If enabled the light will cast shadows. Defaults to false.
 * @property {number} shadowDistance The distance from the viewpoint beyond which shadows are no
 * longer rendered. Affects directional lights only. Defaults to 40.
 * @property {number} shadowIntensity The intensity of the shadow darkening, 1 being shadows are entirely black.
 * Defaults to 1.
 * @property {number} shadowResolution The size of the texture used for the shadow map. Valid sizes
 * are 64, 128, 256, 512, 1024, 2048. Defaults to 1024.
 * @property {number} shadowBias The depth bias for tuning the appearance of the shadow mapping
 * generated by this light. Valid range is 0 to 1. Defaults to 0.05.
 * @property {number} numCascades Number of shadow cascades. Can be 1, 2, 3 or 4. Defaults to 1,
 * representing no cascades.
 * @property {number} cascadeDistribution The distribution of subdivision of the camera frustum for
 * individual shadow cascades. Only used if {@link LightComponent#numCascades} is larger than 1.
 * Can be a value in range of 0 and 1. Value of 0 represents a linear distribution, value of 1
 * represents a logarithmic distribution. Defaults to 0.5. Larger value increases the resolution of
 * the shadows in the near distance.
 * @property {number} normalOffsetBias Normal offset depth bias. Valid range is 0 to 1. Defaults to
 * 0.
 * @property {number} range The range of the light. Affects omni and spot lights only. Defaults to
 * 10.
 * @property {number} innerConeAngle The angle at which the spotlight cone starts to fade off. The
 * angle is specified in degrees. Affects spot lights only. Defaults to 40.
 * @property {number} outerConeAngle The angle at which the spotlight cone has faded to nothing.
 * The angle is specified in degrees. Affects spot lights only. Defaults to 45.
 * @property {number} penumbraSize Size of penumbra for contact hardening shadows. For area lights
 * acts as a multiplier with the dimensions of the area light. For punctual and directional lights
 * it's the area size of the light. Defaults to 1.0.
 * @property {number} falloffMode Controls the rate at which a light attenuates from its position.
 * Can be:
 *
 * - {@link LIGHTFALLOFF_LINEAR}: Linear.
 * - {@link LIGHTFALLOFF_INVERSESQUARED}: Inverse squared.
 *
 * Affects omni and spot lights only. Defaults to {@link LIGHTFALLOFF_LINEAR}.
 * @property {number} mask Defines a mask to determine which {@link MeshInstance}s are lit by this
 * light. Defaults to 1.
 * @property {boolean} affectDynamic If enabled the light will affect non-lightmapped objects.
 * @property {boolean} affectLightmapped If enabled the light will affect lightmapped objects.
 * @property {boolean} bake If enabled the light will be rendered into lightmaps.
 * @property {number} bakeNumSamples If bake is true, this specifies the number of samples used to
 * bake this light into the lightmap. Defaults to 1. Maximum value is 255.
 * @property {number} bakeArea If bake is true and the light type is {@link LIGHTTYPE_DIRECTIONAL},
 * this specifies the penumbra angle in degrees, allowing a soft shadow boundary. Defaults to 0.
 * @property {boolean} bakeDir If enabled and bake=true, the light's direction will contribute to
 * directional lightmaps. Be aware, that directional lightmap is an approximation and can only hold
 * single direction per pixel. Intersecting multiple lights with bakeDir=true may lead to incorrect
 * look of specular/bump-mapping in the area of intersection. The error is not always visible
 * though, and highly scene-dependent.
 * @property {number} shadowUpdateMode Tells the renderer how often shadows must be updated for
 * this light. Can be:
 *
 * - {@link SHADOWUPDATE_NONE}: Don't render shadows.
 * - {@link SHADOWUPDATE_THISFRAME}: Render shadows only once (then automatically switches to
 * {@link SHADOWUPDATE_NONE}.
 * - {@link SHADOWUPDATE_REALTIME}: Render shadows every frame (default).
 * @property {number} shadowType Type of shadows being rendered by this light. Options:
 *
 * - {@link SHADOW_PCF3}: Render depth (color-packed on WebGL 1.0), can be used for PCF 3x3
 * sampling.
 * - {@link SHADOW_VSM8}: Render packed variance shadow map. All shadow receivers must also cast
 * shadows for this mode to work correctly.
 * - {@link SHADOW_VSM16}: Render 16-bit exponential variance shadow map. Requires
 * OES_texture_half_float extension. Falls back to {@link SHADOW_VSM8}, if not supported.
 * - {@link SHADOW_VSM32}: Render 32-bit exponential variance shadow map. Requires
 * OES_texture_float extension. Falls back to {@link SHADOW_VSM16}, if not supported.
 * - {@link SHADOW_PCF5}: Render depth buffer only, can be used for hardware-accelerated PCF 5x5
 * sampling. Requires WebGL2. Falls back to {@link SHADOW_PCF3} on WebGL 1.0.
 * - {@link SHADOW_PCSS}: Render depth as color, and use the software sampled PCSS method for shadows.
 * @property {number} vsmBlurMode Blurring mode for variance shadow maps. Can be:
 *
 * - {@link BLUR_BOX}: Box filter.
 * - {@link BLUR_GAUSSIAN}: Gaussian filter. May look smoother than box, but requires more samples.
 * @property {number} vsmBlurSize Number of samples used for blurring a variance shadow map. Only
 * uneven numbers work, even are incremented. Minimum value is 1, maximum is 25. Defaults to 11.
 * @property {number} cookieAsset Asset that has texture that will be assigned to cookie internally
 * once asset resource is available.
 * @property {Texture} cookie Projection texture. Must be 2D for spot and cubemap for omni light
 * (ignored if incorrect type is used).
 * @property {number} cookieIntensity Projection texture intensity (default is 1).
 * @property {boolean} cookieFalloff Toggle normal spotlight falloff when projection texture is
 * used. When set to false, spotlight will work like a pure texture projector (only fading with
 * distance). Default is false.
 * @property {string} cookieChannel Color channels of the projection texture to use. Can be "r",
 * "g", "b", "a", "rgb".
 * @property {number} cookieAngle Angle for spotlight cookie rotation.
 * @property {import('../../../core/math/vec2.js').Vec2} cookieScale Spotlight cookie scale.
 * @property {import('../../../core/math/vec2.js').Vec2} cookieOffset Spotlight cookie position
 * offset.
 * @property {boolean} isStatic Mark light as non-movable (optimization).
 * @property {number[]} layers An array of layer IDs ({@link Layer#id}) to which this light should
 * belong. Don't push/pop/splice or modify this array, if you want to change it - set a new one
 * instead.
 * @augments Component
 * @category Graphics
 */
class LightComponent extends Component {
  /**
   * Creates a new LightComponent instance.
   *
   * @param {import('./system.js').LightComponentSystem} system - The ComponentSystem that
   * created this Component.
   * @param {import('../../entity.js').Entity} entity - The Entity that this Component is
   * attached to.
   */
  constructor(system, entity) {
    super(system, entity);
    this._cookieAsset = null;
    this._cookieAssetId = null;
    this._cookieAssetAdd = false;
    this._cookieMatrix = null;
  }
  addLightToLayers() {
    for (let i = 0; i < this.layers.length; i++) {
      const layer = this.system.app.scene.layers.getLayerById(this.layers[i]);
      if (layer) {
        layer.addLight(this);
        this.light.addLayer(layer);
      }
    }
  }
  removeLightFromLayers() {
    for (let i = 0; i < this.layers.length; i++) {
      const layer = this.system.app.scene.layers.getLayerById(this.layers[i]);
      if (layer) {
        layer.removeLight(this);
        this.light.removeLayer(layer);
      }
    }
  }
  onLayersChanged(oldComp, newComp) {
    if (this.enabled && this.entity.enabled) {
      this.addLightToLayers();
    }
    oldComp.off('add', this.onLayerAdded, this);
    oldComp.off('remove', this.onLayerRemoved, this);
    newComp.on('add', this.onLayerAdded, this);
    newComp.on('remove', this.onLayerRemoved, this);
  }
  onLayerAdded(layer) {
    const index = this.layers.indexOf(layer.id);
    if (index >= 0 && this.enabled && this.entity.enabled) {
      layer.addLight(this);
      this.light.addLayer(layer);
    }
  }
  onLayerRemoved(layer) {
    const index = this.layers.indexOf(layer.id);
    if (index >= 0) {
      layer.removeLight(this);
      this.light.removeLayer(layer);
    }
  }
  refreshProperties() {
    for (let i = 0; i < _lightProps.length; i++) {
      const name = _lightProps[i];

      /* eslint-disable no-self-assign */
      this[name] = this[name];
      /* eslint-enable no-self-assign */
    }

    if (this.enabled && this.entity.enabled) this.onEnable();
  }
  onCookieAssetSet() {
    let forceLoad = false;
    if (this._cookieAsset.type === 'cubemap' && !this._cookieAsset.loadFaces) {
      this._cookieAsset.loadFaces = true;
      forceLoad = true;
    }
    if (!this._cookieAsset.resource || forceLoad) this.system.app.assets.load(this._cookieAsset);
    if (this._cookieAsset.resource) this.onCookieAssetLoad();
  }
  onCookieAssetAdd(asset) {
    if (this._cookieAssetId !== asset.id) return;
    this._cookieAsset = asset;
    if (this.light.enabled) this.onCookieAssetSet();
    this._cookieAsset.on('load', this.onCookieAssetLoad, this);
    this._cookieAsset.on('remove', this.onCookieAssetRemove, this);
  }
  onCookieAssetLoad() {
    if (!this._cookieAsset || !this._cookieAsset.resource) return;
    this.cookie = this._cookieAsset.resource;
  }
  onCookieAssetRemove() {
    if (!this._cookieAssetId) return;
    if (this._cookieAssetAdd) {
      this.system.app.assets.off('add:' + this._cookieAssetId, this.onCookieAssetAdd, this);
      this._cookieAssetAdd = false;
    }
    if (this._cookieAsset) {
      this._cookieAsset.off('load', this.onCookieAssetLoad, this);
      this._cookieAsset.off('remove', this.onCookieAssetRemove, this);
      this._cookieAsset = null;
    }
    this.cookie = null;
  }
  onEnable() {
    this.light.enabled = true;
    this.system.app.scene.on('set:layers', this.onLayersChanged, this);
    if (this.system.app.scene.layers) {
      this.system.app.scene.layers.on('add', this.onLayerAdded, this);
      this.system.app.scene.layers.on('remove', this.onLayerRemoved, this);
    }
    if (this.enabled && this.entity.enabled) {
      this.addLightToLayers();
    }
    if (this._cookieAsset && !this.cookie) this.onCookieAssetSet();
  }
  onDisable() {
    this.light.enabled = false;
    this.system.app.scene.off('set:layers', this.onLayersChanged, this);
    if (this.system.app.scene.layers) {
      this.system.app.scene.layers.off('add', this.onLayerAdded, this);
      this.system.app.scene.layers.off('remove', this.onLayerRemoved, this);
    }
    this.removeLightFromLayers();
  }
  onRemove() {
    // remove from layers
    this.onDisable();

    // destroy light node
    this.light.destroy();

    // remove cookie asset events
    this.cookieAsset = null;
  }

  /**
   * Returns an array of SHADOWUPDATE_ settings per shadow cascade, or undefined if not used.
   *
   * @type {number[] | null}
   */
  set shadowUpdateOverrides(values) {
    this.light.shadowUpdateOverrides = values;
  }
  get shadowUpdateOverrides() {
    return this.light.shadowUpdateOverrides;
  }
  set penumbraSize(value) {
    this.light.penumbraSize = value;
  }
  get penumbraSize() {
    return this.light.penumbraSize;
  }
}
function _defineProperty(name, defaultValue, setFunc, skipEqualsCheck) {
  const c = LightComponent.prototype;
  _lightProps.push(name);
  _lightPropsDefault.push(defaultValue);
  Object.defineProperty(c, name, {
    get: function () {
      return this.data[name];
    },
    set: function (value) {
      const data = this.data;
      const oldValue = data[name];
      if (!skipEqualsCheck && oldValue === value) return;
      data[name] = value;
      if (setFunc) setFunc.call(this, value, oldValue);
    },
    configurable: true
  });
}
function _defineProps() {
  _defineProperty('enabled', true, function (newValue, oldValue) {
    this.onSetEnabled(null, oldValue, newValue);
  });
  _defineProperty('light', null);
  _defineProperty('type', 'directional', function (newValue, oldValue) {
    this.system.changeType(this, oldValue, newValue);
    // refresh light properties because changing the type does not reset the
    // light properties
    this.refreshProperties();
  });
  _defineProperty('color', new Color(1, 1, 1), function (newValue, oldValue) {
    this.light.setColor(newValue);
  }, true);
  _defineProperty('intensity', 1, function (newValue, oldValue) {
    this.light.intensity = newValue;
  });
  _defineProperty('luminance', 0, function (newValue, oldValue) {
    this.light.luminance = newValue;
  });
  _defineProperty('shape', LIGHTSHAPE_PUNCTUAL, function (newValue, oldValue) {
    this.light.shape = newValue;
  });
  _defineProperty('affectSpecularity', true, function (newValue, oldValue) {
    this.light.affectSpecularity = newValue;
  });
  _defineProperty('castShadows', false, function (newValue, oldValue) {
    this.light.castShadows = newValue;
  });
  _defineProperty('shadowDistance', 40, function (newValue, oldValue) {
    this.light.shadowDistance = newValue;
  });
  _defineProperty('shadowIntensity', 1, function (newValue, oldValue) {
    this.light.shadowIntensity = newValue;
  });
  _defineProperty('shadowResolution', 1024, function (newValue, oldValue) {
    this.light.shadowResolution = newValue;
  });
  _defineProperty('shadowBias', 0.05, function (newValue, oldValue) {
    this.light.shadowBias = -0.01 * math.clamp(newValue, 0, 1);
  });
  _defineProperty('numCascades', 1, function (newValue, oldValue) {
    this.light.numCascades = math.clamp(Math.floor(newValue), 1, 4);
  });
  _defineProperty('bakeNumSamples', 1, function (newValue, oldValue) {
    this.light.bakeNumSamples = math.clamp(Math.floor(newValue), 1, 255);
  });
  _defineProperty('bakeArea', 0, function (newValue, oldValue) {
    this.light.bakeArea = math.clamp(newValue, 0, 180);
  });
  _defineProperty('cascadeDistribution', 0.5, function (newValue, oldValue) {
    this.light.cascadeDistribution = math.clamp(newValue, 0, 1);
  });
  _defineProperty('normalOffsetBias', 0, function (newValue, oldValue) {
    this.light.normalOffsetBias = math.clamp(newValue, 0, 1);
  });
  _defineProperty('range', 10, function (newValue, oldValue) {
    this.light.attenuationEnd = newValue;
  });
  _defineProperty('innerConeAngle', 40, function (newValue, oldValue) {
    this.light.innerConeAngle = newValue;
  });
  _defineProperty('outerConeAngle', 45, function (newValue, oldValue) {
    this.light.outerConeAngle = newValue;
  });
  _defineProperty('falloffMode', LIGHTFALLOFF_LINEAR, function (newValue, oldValue) {
    this.light.falloffMode = newValue;
  });
  _defineProperty('shadowType', SHADOW_PCF3, function (newValue, oldValue) {
    this.light.shadowType = newValue;
  });
  _defineProperty('vsmBlurSize', 11, function (newValue, oldValue) {
    this.light.vsmBlurSize = newValue;
  });
  _defineProperty('vsmBlurMode', BLUR_GAUSSIAN, function (newValue, oldValue) {
    this.light.vsmBlurMode = newValue;
  });
  _defineProperty('vsmBias', 0.01 * 0.25, function (newValue, oldValue) {
    this.light.vsmBias = math.clamp(newValue, 0, 1);
  });
  _defineProperty('cookieAsset', null, function (newValue, oldValue) {
    if (this._cookieAssetId && (newValue instanceof Asset && newValue.id === this._cookieAssetId || newValue === this._cookieAssetId)) return;
    this.onCookieAssetRemove();
    this._cookieAssetId = null;
    if (newValue instanceof Asset) {
      this.data.cookieAsset = newValue.id;
      this._cookieAssetId = newValue.id;
      this.onCookieAssetAdd(newValue);
    } else if (typeof newValue === 'number') {
      this._cookieAssetId = newValue;
      const asset = this.system.app.assets.get(newValue);
      if (asset) {
        this.onCookieAssetAdd(asset);
      } else {
        this._cookieAssetAdd = true;
        this.system.app.assets.on('add:' + this._cookieAssetId, this.onCookieAssetAdd, this);
      }
    }
  });
  _defineProperty('cookie', null, function (newValue, oldValue) {
    this.light.cookie = newValue;
  });
  _defineProperty('cookieIntensity', 1, function (newValue, oldValue) {
    this.light.cookieIntensity = math.clamp(newValue, 0, 1);
  });
  _defineProperty('cookieFalloff', true, function (newValue, oldValue) {
    this.light.cookieFalloff = newValue;
  });
  _defineProperty('cookieChannel', 'rgb', function (newValue, oldValue) {
    this.light.cookieChannel = newValue;
  });
  _defineProperty('cookieAngle', 0, function (newValue, oldValue) {
    if (newValue !== 0 || this.cookieScale !== null) {
      if (!this._cookieMatrix) this._cookieMatrix = new Vec4();
      let scx = 1;
      let scy = 1;
      if (this.cookieScale) {
        scx = this.cookieScale.x;
        scy = this.cookieScale.y;
      }
      const c = Math.cos(newValue * math.DEG_TO_RAD);
      const s = Math.sin(newValue * math.DEG_TO_RAD);
      this._cookieMatrix.set(c / scx, -s / scx, s / scy, c / scy);
      this.light.cookieTransform = this._cookieMatrix;
    } else {
      this.light.cookieTransform = null;
    }
  });
  _defineProperty('cookieScale', null, function (newValue, oldValue) {
    if (newValue !== null || this.cookieAngle !== 0) {
      if (!this._cookieMatrix) this._cookieMatrix = new Vec4();
      const scx = newValue.x;
      const scy = newValue.y;
      const c = Math.cos(this.cookieAngle * math.DEG_TO_RAD);
      const s = Math.sin(this.cookieAngle * math.DEG_TO_RAD);
      this._cookieMatrix.set(c / scx, -s / scx, s / scy, c / scy);
      this.light.cookieTransform = this._cookieMatrix;
    } else {
      this.light.cookieTransform = null;
    }
  }, true);
  _defineProperty('cookieOffset', null, function (newValue, oldValue) {
    this.light.cookieOffset = newValue;
  }, true);
  _defineProperty('shadowUpdateMode', SHADOWUPDATE_REALTIME, function (newValue, oldValue) {
    this.light.shadowUpdateMode = newValue;
  }, true);
  _defineProperty('mask', 1, function (newValue, oldValue) {
    this.light.mask = newValue;
  });
  _defineProperty('affectDynamic', true, function (newValue, oldValue) {
    if (newValue) {
      this.light.mask |= MASK_AFFECT_DYNAMIC;
    } else {
      this.light.mask &= ~MASK_AFFECT_DYNAMIC;
    }
    this.light.layersDirty();
  });
  _defineProperty('affectLightmapped', false, function (newValue, oldValue) {
    if (newValue) {
      this.light.mask |= MASK_AFFECT_LIGHTMAPPED;
      if (this.bake) this.light.mask &= ~MASK_BAKE;
    } else {
      this.light.mask &= ~MASK_AFFECT_LIGHTMAPPED;
      if (this.bake) this.light.mask |= MASK_BAKE;
    }
  });
  _defineProperty('bake', false, function (newValue, oldValue) {
    if (newValue) {
      this.light.mask |= MASK_BAKE;
      if (this.affectLightmapped) this.light.mask &= ~MASK_AFFECT_LIGHTMAPPED;
    } else {
      this.light.mask &= ~MASK_BAKE;
      if (this.affectLightmapped) this.light.mask |= MASK_AFFECT_LIGHTMAPPED;
    }
    this.light.layersDirty();
  });
  _defineProperty('bakeDir', true, function (newValue, oldValue) {
    this.light.bakeDir = newValue;
  });
  _defineProperty('isStatic', false, function (newValue, oldValue) {
    this.light.isStatic = newValue;
  });
  _defineProperty('layers', [LAYERID_WORLD], function (newValue, oldValue) {
    for (let i = 0; i < oldValue.length; i++) {
      const layer = this.system.app.scene.layers.getLayerById(oldValue[i]);
      if (!layer) continue;
      layer.removeLight(this);
      this.light.removeLayer(layer);
    }
    for (let i = 0; i < newValue.length; i++) {
      const layer = this.system.app.scene.layers.getLayerById(newValue[i]);
      if (!layer) continue;
      if (this.enabled && this.entity.enabled) {
        layer.addLight(this);
        this.light.addLayer(layer);
      }
    }
  });
  _lightProps.push("penumbraSize");
  _lightPropsDefault.push(1);
}
_defineProps();

export { LightComponent, _lightProps, _lightPropsDefault };
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY29tcG9uZW50LmpzIiwic291cmNlcyI6WyIuLi8uLi8uLi8uLi8uLi8uLi8uLi9zcmMvZnJhbWV3b3JrL2NvbXBvbmVudHMvbGlnaHQvY29tcG9uZW50LmpzIl0sInNvdXJjZXNDb250ZW50IjpbImltcG9ydCB7IG1hdGggfSBmcm9tICcuLi8uLi8uLi9jb3JlL21hdGgvbWF0aC5qcyc7XG5pbXBvcnQgeyBDb2xvciB9IGZyb20gJy4uLy4uLy4uL2NvcmUvbWF0aC9jb2xvci5qcyc7XG5pbXBvcnQgeyBWZWM0IH0gZnJvbSAnLi4vLi4vLi4vY29yZS9tYXRoL3ZlYzQuanMnO1xuXG5pbXBvcnQge1xuICAgIEJMVVJfR0FVU1NJQU4sXG4gICAgTEFZRVJJRF9XT1JMRCxcbiAgICBMSUdIVFNIQVBFX1BVTkNUVUFMLFxuICAgIExJR0hURkFMTE9GRl9MSU5FQVIsXG4gICAgTUFTS19BRkZFQ1RfTElHSFRNQVBQRUQsIE1BU0tfQUZGRUNUX0RZTkFNSUMsIE1BU0tfQkFLRSxcbiAgICBTSEFET1dfUENGMyxcbiAgICBTSEFET1dVUERBVEVfUkVBTFRJTUVcbn0gZnJvbSAnLi4vLi4vLi4vc2NlbmUvY29uc3RhbnRzLmpzJztcblxuaW1wb3J0IHsgQXNzZXQgfSBmcm9tICcuLi8uLi9hc3NldC9hc3NldC5qcyc7XG5cbmltcG9ydCB7IENvbXBvbmVudCB9IGZyb20gJy4uL2NvbXBvbmVudC5qcyc7XG5cbmNvbnN0IF9saWdodFByb3BzID0gW107XG5jb25zdCBfbGlnaHRQcm9wc0RlZmF1bHQgPSBbXTtcblxuLyoqXG4gKiBUaGUgTGlnaHQgQ29tcG9uZW50IGVuYWJsZXMgdGhlIEVudGl0eSB0byBsaWdodCB0aGUgc2NlbmUuIFRoZXJlIGFyZSB0aHJlZSB0eXBlcyBvZiBsaWdodDpcbiAqIGRpcmVjdGlvbmFsLCBvbW5pIGFuZCBzcG90LiBEaXJlY3Rpb25hbCBsaWdodHMgYXJlIGdsb2JhbCBpbiB0aGF0IHRoZXkgYXJlIGNvbnNpZGVyZWQgdG8gYmVcbiAqIGluZmluaXRlbHkgZmFyIGF3YXkgYW5kIGxpZ2h0IHRoZSBlbnRpcmUgc2NlbmUuIE9tbmkgYW5kIHNwb3QgbGlnaHRzIGFyZSBsb2NhbCBpbiB0aGF0IHRoZXkgaGF2ZVxuICogYSBwb3NpdGlvbiBhbmQgYSByYW5nZS4gQSBzcG90IGxpZ2h0IGlzIGEgc3BlY2lhbGl6YXRpb24gb2YgYW4gb21uaSBsaWdodCB3aGVyZSBsaWdodCBpcyBlbWl0dGVkXG4gKiBpbiBhIGNvbmUgcmF0aGVyIHRoYW4gaW4gYWxsIGRpcmVjdGlvbnMuIExpZ2h0cyBhbHNvIGhhdmUgdGhlIGFiaWxpdHkgdG8gY2FzdCBzaGFkb3dzIHRvIGFkZFxuICogcmVhbGlzbSB0byB5b3VyIHNjZW5lcy5cbiAqXG4gKiBgYGBqYXZhc2NyaXB0XG4gKiAvLyBBZGQgYSBwYy5MaWdodENvbXBvbmVudCB0byBhbiBlbnRpdHlcbiAqIGNvbnN0IGVudGl0eSA9IG5ldyBwYy5FbnRpdHkoKTtcbiAqIGVudGl0eS5hZGRDb21wb25lbnQoJ2xpZ2h0Jywge1xuICogICAgIHR5cGU6IFwib21uaVwiLFxuICogICAgIGNvbG9yOiBuZXcgcGMuQ29sb3IoMSwgMCwgMCksXG4gKiAgICAgcmFuZ2U6IDEwXG4gKiB9KTtcbiAqXG4gKiAvLyBHZXQgdGhlIHBjLkxpZ2h0Q29tcG9uZW50IG9uIGFuIGVudGl0eVxuICogY29uc3QgbGlnaHRDb21wb25lbnQgPSBlbnRpdHkubGlnaHQ7XG4gKlxuICogLy8gVXBkYXRlIGEgcHJvcGVydHkgb24gYSBsaWdodCBjb21wb25lbnRcbiAqIGVudGl0eS5saWdodC5yYW5nZSA9IDIwO1xuICogYGBgXG4gKlxuICogQHByb3BlcnR5IHtzdHJpbmd9IHR5cGUgVGhlIHR5cGUgb2YgbGlnaHQuIENhbiBiZTpcbiAqXG4gKiAtIFwiZGlyZWN0aW9uYWxcIjogQSBsaWdodCB0aGF0IGlzIGluZmluaXRlbHkgZmFyIGF3YXkgYW5kIGxpZ2h0cyB0aGUgZW50aXJlIHNjZW5lIGZyb20gb25lXG4gKiBkaXJlY3Rpb24uXG4gKiAtIFwib21uaVwiOiBBbiBvbW5pLWRpcmVjdGlvbmFsIGxpZ2h0IHRoYXQgaWxsdW1pbmF0ZXMgaW4gYWxsIGRpcmVjdGlvbnMgZnJvbSB0aGUgbGlnaHQgc291cmNlLlxuICogLSBcInNwb3RcIjogQW4gb21uaS1kaXJlY3Rpb25hbCBsaWdodCBidXQgaXMgYm91bmRlZCBieSBhIGNvbmUuXG4gKlxuICogRGVmYXVsdHMgdG8gXCJkaXJlY3Rpb25hbFwiLlxuICogQHByb3BlcnR5IHtDb2xvcn0gY29sb3IgVGhlIENvbG9yIG9mIHRoZSBsaWdodC4gVGhlIGFscGhhIGNvbXBvbmVudCBvZiB0aGUgY29sb3IgaXMgaWdub3JlZC5cbiAqIERlZmF1bHRzIHRvIHdoaXRlICgxLCAxLCAxKS5cbiAqIEBwcm9wZXJ0eSB7bnVtYmVyfSBpbnRlbnNpdHkgVGhlIGJyaWdodG5lc3Mgb2YgdGhlIGxpZ2h0LiBEZWZhdWx0cyB0byAxLlxuICogQHByb3BlcnR5IHtudW1iZXJ9IGx1bWluYW5jZSBUaGUgcGh5c2ljYWxseSBiYXNlZCBsdW1pbmFuY2UuIE9ubHkgdXNlZCBpZiBzY2VuZS5waHlzaWNhbFVuaXRzIGlzIHRydWUuIERlZmF1bHRzIHRvIDAuXG4gKiBAcHJvcGVydHkge251bWJlcn0gc2hhcGUgVGhlIGxpZ2h0IHNvdXJjZSBzaGFwZS4gQ2FuIGJlOlxuICpcbiAqIC0ge0BsaW5rIExJR0hUU0hBUEVfUFVOQ1RVQUx9OiBJbmZpbml0ZXNpbWFsbHkgc21hbGwgcG9pbnQuXG4gKiAtIHtAbGluayBMSUdIVFNIQVBFX1JFQ1R9OiBSZWN0YW5nbGUgc2hhcGUuXG4gKiAtIHtAbGluayBMSUdIVFNIQVBFX0RJU0t9OiBEaXNrIHNoYXBlLlxuICogLSB7QGxpbmsgTElHSFRTSEFQRV9TUEhFUkV9OiBTcGhlcmUgc2hhcGUuXG4gKlxuICogRGVmYXVsdHMgdG8gcGMuTElHSFRTSEFQRV9QVU5DVFVBTC5cbiAqIEBwcm9wZXJ0eSB7Ym9vbGVhbn0gYWZmZWN0U3BlY3VsYXJpdHkgSWYgZW5hYmxlZCwgbWF0ZXJpYWwgc3BlY3VsYXJpdHkgd2lsbCBiZSBhZmZlY3RlZCBieSB0aGlzIGxpZ2h0LlxuICogSWdub3JlZCBmb3IgbGlnaHRzIG90aGVyIHRoYW4ge0BsaW5rIExJR0hUVFlQRV9ESVJFQ1RJT05BTH0uIERlZmF1bHRzIHRvIHRydWUuXG4gKiBAcHJvcGVydHkge2Jvb2xlYW59IGNhc3RTaGFkb3dzIElmIGVuYWJsZWQgdGhlIGxpZ2h0IHdpbGwgY2FzdCBzaGFkb3dzLiBEZWZhdWx0cyB0byBmYWxzZS5cbiAqIEBwcm9wZXJ0eSB7bnVtYmVyfSBzaGFkb3dEaXN0YW5jZSBUaGUgZGlzdGFuY2UgZnJvbSB0aGUgdmlld3BvaW50IGJleW9uZCB3aGljaCBzaGFkb3dzIGFyZSBub1xuICogbG9uZ2VyIHJlbmRlcmVkLiBBZmZlY3RzIGRpcmVjdGlvbmFsIGxpZ2h0cyBvbmx5LiBEZWZhdWx0cyB0byA0MC5cbiAqIEBwcm9wZXJ0eSB7bnVtYmVyfSBzaGFkb3dJbnRlbnNpdHkgVGhlIGludGVuc2l0eSBvZiB0aGUgc2hhZG93IGRhcmtlbmluZywgMSBiZWluZyBzaGFkb3dzIGFyZSBlbnRpcmVseSBibGFjay5cbiAqIERlZmF1bHRzIHRvIDEuXG4gKiBAcHJvcGVydHkge251bWJlcn0gc2hhZG93UmVzb2x1dGlvbiBUaGUgc2l6ZSBvZiB0aGUgdGV4dHVyZSB1c2VkIGZvciB0aGUgc2hhZG93IG1hcC4gVmFsaWQgc2l6ZXNcbiAqIGFyZSA2NCwgMTI4LCAyNTYsIDUxMiwgMTAyNCwgMjA0OC4gRGVmYXVsdHMgdG8gMTAyNC5cbiAqIEBwcm9wZXJ0eSB7bnVtYmVyfSBzaGFkb3dCaWFzIFRoZSBkZXB0aCBiaWFzIGZvciB0dW5pbmcgdGhlIGFwcGVhcmFuY2Ugb2YgdGhlIHNoYWRvdyBtYXBwaW5nXG4gKiBnZW5lcmF0ZWQgYnkgdGhpcyBsaWdodC4gVmFsaWQgcmFuZ2UgaXMgMCB0byAxLiBEZWZhdWx0cyB0byAwLjA1LlxuICogQHByb3BlcnR5IHtudW1iZXJ9IG51bUNhc2NhZGVzIE51bWJlciBvZiBzaGFkb3cgY2FzY2FkZXMuIENhbiBiZSAxLCAyLCAzIG9yIDQuIERlZmF1bHRzIHRvIDEsXG4gKiByZXByZXNlbnRpbmcgbm8gY2FzY2FkZXMuXG4gKiBAcHJvcGVydHkge251bWJlcn0gY2FzY2FkZURpc3RyaWJ1dGlvbiBUaGUgZGlzdHJpYnV0aW9uIG9mIHN1YmRpdmlzaW9uIG9mIHRoZSBjYW1lcmEgZnJ1c3R1bSBmb3JcbiAqIGluZGl2aWR1YWwgc2hhZG93IGNhc2NhZGVzLiBPbmx5IHVzZWQgaWYge0BsaW5rIExpZ2h0Q29tcG9uZW50I251bUNhc2NhZGVzfSBpcyBsYXJnZXIgdGhhbiAxLlxuICogQ2FuIGJlIGEgdmFsdWUgaW4gcmFuZ2Ugb2YgMCBhbmQgMS4gVmFsdWUgb2YgMCByZXByZXNlbnRzIGEgbGluZWFyIGRpc3RyaWJ1dGlvbiwgdmFsdWUgb2YgMVxuICogcmVwcmVzZW50cyBhIGxvZ2FyaXRobWljIGRpc3RyaWJ1dGlvbi4gRGVmYXVsdHMgdG8gMC41LiBMYXJnZXIgdmFsdWUgaW5jcmVhc2VzIHRoZSByZXNvbHV0aW9uIG9mXG4gKiB0aGUgc2hhZG93cyBpbiB0aGUgbmVhciBkaXN0YW5jZS5cbiAqIEBwcm9wZXJ0eSB7bnVtYmVyfSBub3JtYWxPZmZzZXRCaWFzIE5vcm1hbCBvZmZzZXQgZGVwdGggYmlhcy4gVmFsaWQgcmFuZ2UgaXMgMCB0byAxLiBEZWZhdWx0cyB0b1xuICogMC5cbiAqIEBwcm9wZXJ0eSB7bnVtYmVyfSByYW5nZSBUaGUgcmFuZ2Ugb2YgdGhlIGxpZ2h0LiBBZmZlY3RzIG9tbmkgYW5kIHNwb3QgbGlnaHRzIG9ubHkuIERlZmF1bHRzIHRvXG4gKiAxMC5cbiAqIEBwcm9wZXJ0eSB7bnVtYmVyfSBpbm5lckNvbmVBbmdsZSBUaGUgYW5nbGUgYXQgd2hpY2ggdGhlIHNwb3RsaWdodCBjb25lIHN0YXJ0cyB0byBmYWRlIG9mZi4gVGhlXG4gKiBhbmdsZSBpcyBzcGVjaWZpZWQgaW4gZGVncmVlcy4gQWZmZWN0cyBzcG90IGxpZ2h0cyBvbmx5LiBEZWZhdWx0cyB0byA0MC5cbiAqIEBwcm9wZXJ0eSB7bnVtYmVyfSBvdXRlckNvbmVBbmdsZSBUaGUgYW5nbGUgYXQgd2hpY2ggdGhlIHNwb3RsaWdodCBjb25lIGhhcyBmYWRlZCB0byBub3RoaW5nLlxuICogVGhlIGFuZ2xlIGlzIHNwZWNpZmllZCBpbiBkZWdyZWVzLiBBZmZlY3RzIHNwb3QgbGlnaHRzIG9ubHkuIERlZmF1bHRzIHRvIDQ1LlxuICogQHByb3BlcnR5IHtudW1iZXJ9IHBlbnVtYnJhU2l6ZSBTaXplIG9mIHBlbnVtYnJhIGZvciBjb250YWN0IGhhcmRlbmluZyBzaGFkb3dzLiBGb3IgYXJlYSBsaWdodHNcbiAqIGFjdHMgYXMgYSBtdWx0aXBsaWVyIHdpdGggdGhlIGRpbWVuc2lvbnMgb2YgdGhlIGFyZWEgbGlnaHQuIEZvciBwdW5jdHVhbCBhbmQgZGlyZWN0aW9uYWwgbGlnaHRzXG4gKiBpdCdzIHRoZSBhcmVhIHNpemUgb2YgdGhlIGxpZ2h0LiBEZWZhdWx0cyB0byAxLjAuXG4gKiBAcHJvcGVydHkge251bWJlcn0gZmFsbG9mZk1vZGUgQ29udHJvbHMgdGhlIHJhdGUgYXQgd2hpY2ggYSBsaWdodCBhdHRlbnVhdGVzIGZyb20gaXRzIHBvc2l0aW9uLlxuICogQ2FuIGJlOlxuICpcbiAqIC0ge0BsaW5rIExJR0hURkFMTE9GRl9MSU5FQVJ9OiBMaW5lYXIuXG4gKiAtIHtAbGluayBMSUdIVEZBTExPRkZfSU5WRVJTRVNRVUFSRUR9OiBJbnZlcnNlIHNxdWFyZWQuXG4gKlxuICogQWZmZWN0cyBvbW5pIGFuZCBzcG90IGxpZ2h0cyBvbmx5LiBEZWZhdWx0cyB0byB7QGxpbmsgTElHSFRGQUxMT0ZGX0xJTkVBUn0uXG4gKiBAcHJvcGVydHkge251bWJlcn0gbWFzayBEZWZpbmVzIGEgbWFzayB0byBkZXRlcm1pbmUgd2hpY2gge0BsaW5rIE1lc2hJbnN0YW5jZX1zIGFyZSBsaXQgYnkgdGhpc1xuICogbGlnaHQuIERlZmF1bHRzIHRvIDEuXG4gKiBAcHJvcGVydHkge2Jvb2xlYW59IGFmZmVjdER5bmFtaWMgSWYgZW5hYmxlZCB0aGUgbGlnaHQgd2lsbCBhZmZlY3Qgbm9uLWxpZ2h0bWFwcGVkIG9iamVjdHMuXG4gKiBAcHJvcGVydHkge2Jvb2xlYW59IGFmZmVjdExpZ2h0bWFwcGVkIElmIGVuYWJsZWQgdGhlIGxpZ2h0IHdpbGwgYWZmZWN0IGxpZ2h0bWFwcGVkIG9iamVjdHMuXG4gKiBAcHJvcGVydHkge2Jvb2xlYW59IGJha2UgSWYgZW5hYmxlZCB0aGUgbGlnaHQgd2lsbCBiZSByZW5kZXJlZCBpbnRvIGxpZ2h0bWFwcy5cbiAqIEBwcm9wZXJ0eSB7bnVtYmVyfSBiYWtlTnVtU2FtcGxlcyBJZiBiYWtlIGlzIHRydWUsIHRoaXMgc3BlY2lmaWVzIHRoZSBudW1iZXIgb2Ygc2FtcGxlcyB1c2VkIHRvXG4gKiBiYWtlIHRoaXMgbGlnaHQgaW50byB0aGUgbGlnaHRtYXAuIERlZmF1bHRzIHRvIDEuIE1heGltdW0gdmFsdWUgaXMgMjU1LlxuICogQHByb3BlcnR5IHtudW1iZXJ9IGJha2VBcmVhIElmIGJha2UgaXMgdHJ1ZSBhbmQgdGhlIGxpZ2h0IHR5cGUgaXMge0BsaW5rIExJR0hUVFlQRV9ESVJFQ1RJT05BTH0sXG4gKiB0aGlzIHNwZWNpZmllcyB0aGUgcGVudW1icmEgYW5nbGUgaW4gZGVncmVlcywgYWxsb3dpbmcgYSBzb2Z0IHNoYWRvdyBib3VuZGFyeS4gRGVmYXVsdHMgdG8gMC5cbiAqIEBwcm9wZXJ0eSB7Ym9vbGVhbn0gYmFrZURpciBJZiBlbmFibGVkIGFuZCBiYWtlPXRydWUsIHRoZSBsaWdodCdzIGRpcmVjdGlvbiB3aWxsIGNvbnRyaWJ1dGUgdG9cbiAqIGRpcmVjdGlvbmFsIGxpZ2h0bWFwcy4gQmUgYXdhcmUsIHRoYXQgZGlyZWN0aW9uYWwgbGlnaHRtYXAgaXMgYW4gYXBwcm94aW1hdGlvbiBhbmQgY2FuIG9ubHkgaG9sZFxuICogc2luZ2xlIGRpcmVjdGlvbiBwZXIgcGl4ZWwuIEludGVyc2VjdGluZyBtdWx0aXBsZSBsaWdodHMgd2l0aCBiYWtlRGlyPXRydWUgbWF5IGxlYWQgdG8gaW5jb3JyZWN0XG4gKiBsb29rIG9mIHNwZWN1bGFyL2J1bXAtbWFwcGluZyBpbiB0aGUgYXJlYSBvZiBpbnRlcnNlY3Rpb24uIFRoZSBlcnJvciBpcyBub3QgYWx3YXlzIHZpc2libGVcbiAqIHRob3VnaCwgYW5kIGhpZ2hseSBzY2VuZS1kZXBlbmRlbnQuXG4gKiBAcHJvcGVydHkge251bWJlcn0gc2hhZG93VXBkYXRlTW9kZSBUZWxscyB0aGUgcmVuZGVyZXIgaG93IG9mdGVuIHNoYWRvd3MgbXVzdCBiZSB1cGRhdGVkIGZvclxuICogdGhpcyBsaWdodC4gQ2FuIGJlOlxuICpcbiAqIC0ge0BsaW5rIFNIQURPV1VQREFURV9OT05FfTogRG9uJ3QgcmVuZGVyIHNoYWRvd3MuXG4gKiAtIHtAbGluayBTSEFET1dVUERBVEVfVEhJU0ZSQU1FfTogUmVuZGVyIHNoYWRvd3Mgb25seSBvbmNlICh0aGVuIGF1dG9tYXRpY2FsbHkgc3dpdGNoZXMgdG9cbiAqIHtAbGluayBTSEFET1dVUERBVEVfTk9ORX0uXG4gKiAtIHtAbGluayBTSEFET1dVUERBVEVfUkVBTFRJTUV9OiBSZW5kZXIgc2hhZG93cyBldmVyeSBmcmFtZSAoZGVmYXVsdCkuXG4gKiBAcHJvcGVydHkge251bWJlcn0gc2hhZG93VHlwZSBUeXBlIG9mIHNoYWRvd3MgYmVpbmcgcmVuZGVyZWQgYnkgdGhpcyBsaWdodC4gT3B0aW9uczpcbiAqXG4gKiAtIHtAbGluayBTSEFET1dfUENGM306IFJlbmRlciBkZXB0aCAoY29sb3ItcGFja2VkIG9uIFdlYkdMIDEuMCksIGNhbiBiZSB1c2VkIGZvciBQQ0YgM3gzXG4gKiBzYW1wbGluZy5cbiAqIC0ge0BsaW5rIFNIQURPV19WU004fTogUmVuZGVyIHBhY2tlZCB2YXJpYW5jZSBzaGFkb3cgbWFwLiBBbGwgc2hhZG93IHJlY2VpdmVycyBtdXN0IGFsc28gY2FzdFxuICogc2hhZG93cyBmb3IgdGhpcyBtb2RlIHRvIHdvcmsgY29ycmVjdGx5LlxuICogLSB7QGxpbmsgU0hBRE9XX1ZTTTE2fTogUmVuZGVyIDE2LWJpdCBleHBvbmVudGlhbCB2YXJpYW5jZSBzaGFkb3cgbWFwLiBSZXF1aXJlc1xuICogT0VTX3RleHR1cmVfaGFsZl9mbG9hdCBleHRlbnNpb24uIEZhbGxzIGJhY2sgdG8ge0BsaW5rIFNIQURPV19WU004fSwgaWYgbm90IHN1cHBvcnRlZC5cbiAqIC0ge0BsaW5rIFNIQURPV19WU00zMn06IFJlbmRlciAzMi1iaXQgZXhwb25lbnRpYWwgdmFyaWFuY2Ugc2hhZG93IG1hcC4gUmVxdWlyZXNcbiAqIE9FU190ZXh0dXJlX2Zsb2F0IGV4dGVuc2lvbi4gRmFsbHMgYmFjayB0byB7QGxpbmsgU0hBRE9XX1ZTTTE2fSwgaWYgbm90IHN1cHBvcnRlZC5cbiAqIC0ge0BsaW5rIFNIQURPV19QQ0Y1fTogUmVuZGVyIGRlcHRoIGJ1ZmZlciBvbmx5LCBjYW4gYmUgdXNlZCBmb3IgaGFyZHdhcmUtYWNjZWxlcmF0ZWQgUENGIDV4NVxuICogc2FtcGxpbmcuIFJlcXVpcmVzIFdlYkdMMi4gRmFsbHMgYmFjayB0byB7QGxpbmsgU0hBRE9XX1BDRjN9IG9uIFdlYkdMIDEuMC5cbiAqIC0ge0BsaW5rIFNIQURPV19QQ1NTfTogUmVuZGVyIGRlcHRoIGFzIGNvbG9yLCBhbmQgdXNlIHRoZSBzb2Z0d2FyZSBzYW1wbGVkIFBDU1MgbWV0aG9kIGZvciBzaGFkb3dzLlxuICogQHByb3BlcnR5IHtudW1iZXJ9IHZzbUJsdXJNb2RlIEJsdXJyaW5nIG1vZGUgZm9yIHZhcmlhbmNlIHNoYWRvdyBtYXBzLiBDYW4gYmU6XG4gKlxuICogLSB7QGxpbmsgQkxVUl9CT1h9OiBCb3ggZmlsdGVyLlxuICogLSB7QGxpbmsgQkxVUl9HQVVTU0lBTn06IEdhdXNzaWFuIGZpbHRlci4gTWF5IGxvb2sgc21vb3RoZXIgdGhhbiBib3gsIGJ1dCByZXF1aXJlcyBtb3JlIHNhbXBsZXMuXG4gKiBAcHJvcGVydHkge251bWJlcn0gdnNtQmx1clNpemUgTnVtYmVyIG9mIHNhbXBsZXMgdXNlZCBmb3IgYmx1cnJpbmcgYSB2YXJpYW5jZSBzaGFkb3cgbWFwLiBPbmx5XG4gKiB1bmV2ZW4gbnVtYmVycyB3b3JrLCBldmVuIGFyZSBpbmNyZW1lbnRlZC4gTWluaW11bSB2YWx1ZSBpcyAxLCBtYXhpbXVtIGlzIDI1LiBEZWZhdWx0cyB0byAxMS5cbiAqIEBwcm9wZXJ0eSB7bnVtYmVyfSBjb29raWVBc3NldCBBc3NldCB0aGF0IGhhcyB0ZXh0dXJlIHRoYXQgd2lsbCBiZSBhc3NpZ25lZCB0byBjb29raWUgaW50ZXJuYWxseVxuICogb25jZSBhc3NldCByZXNvdXJjZSBpcyBhdmFpbGFibGUuXG4gKiBAcHJvcGVydHkge1RleHR1cmV9IGNvb2tpZSBQcm9qZWN0aW9uIHRleHR1cmUuIE11c3QgYmUgMkQgZm9yIHNwb3QgYW5kIGN1YmVtYXAgZm9yIG9tbmkgbGlnaHRcbiAqIChpZ25vcmVkIGlmIGluY29ycmVjdCB0eXBlIGlzIHVzZWQpLlxuICogQHByb3BlcnR5IHtudW1iZXJ9IGNvb2tpZUludGVuc2l0eSBQcm9qZWN0aW9uIHRleHR1cmUgaW50ZW5zaXR5IChkZWZhdWx0IGlzIDEpLlxuICogQHByb3BlcnR5IHtib29sZWFufSBjb29raWVGYWxsb2ZmIFRvZ2dsZSBub3JtYWwgc3BvdGxpZ2h0IGZhbGxvZmYgd2hlbiBwcm9qZWN0aW9uIHRleHR1cmUgaXNcbiAqIHVzZWQuIFdoZW4gc2V0IHRvIGZhbHNlLCBzcG90bGlnaHQgd2lsbCB3b3JrIGxpa2UgYSBwdXJlIHRleHR1cmUgcHJvamVjdG9yIChvbmx5IGZhZGluZyB3aXRoXG4gKiBkaXN0YW5jZSkuIERlZmF1bHQgaXMgZmFsc2UuXG4gKiBAcHJvcGVydHkge3N0cmluZ30gY29va2llQ2hhbm5lbCBDb2xvciBjaGFubmVscyBvZiB0aGUgcHJvamVjdGlvbiB0ZXh0dXJlIHRvIHVzZS4gQ2FuIGJlIFwiclwiLFxuICogXCJnXCIsIFwiYlwiLCBcImFcIiwgXCJyZ2JcIi5cbiAqIEBwcm9wZXJ0eSB7bnVtYmVyfSBjb29raWVBbmdsZSBBbmdsZSBmb3Igc3BvdGxpZ2h0IGNvb2tpZSByb3RhdGlvbi5cbiAqIEBwcm9wZXJ0eSB7aW1wb3J0KCcuLi8uLi8uLi9jb3JlL21hdGgvdmVjMi5qcycpLlZlYzJ9IGNvb2tpZVNjYWxlIFNwb3RsaWdodCBjb29raWUgc2NhbGUuXG4gKiBAcHJvcGVydHkge2ltcG9ydCgnLi4vLi4vLi4vY29yZS9tYXRoL3ZlYzIuanMnKS5WZWMyfSBjb29raWVPZmZzZXQgU3BvdGxpZ2h0IGNvb2tpZSBwb3NpdGlvblxuICogb2Zmc2V0LlxuICogQHByb3BlcnR5IHtib29sZWFufSBpc1N0YXRpYyBNYXJrIGxpZ2h0IGFzIG5vbi1tb3ZhYmxlIChvcHRpbWl6YXRpb24pLlxuICogQHByb3BlcnR5IHtudW1iZXJbXX0gbGF5ZXJzIEFuIGFycmF5IG9mIGxheWVyIElEcyAoe0BsaW5rIExheWVyI2lkfSkgdG8gd2hpY2ggdGhpcyBsaWdodCBzaG91bGRcbiAqIGJlbG9uZy4gRG9uJ3QgcHVzaC9wb3Avc3BsaWNlIG9yIG1vZGlmeSB0aGlzIGFycmF5LCBpZiB5b3Ugd2FudCB0byBjaGFuZ2UgaXQgLSBzZXQgYSBuZXcgb25lXG4gKiBpbnN0ZWFkLlxuICogQGF1Z21lbnRzIENvbXBvbmVudFxuICogQGNhdGVnb3J5IEdyYXBoaWNzXG4gKi9cbmNsYXNzIExpZ2h0Q29tcG9uZW50IGV4dGVuZHMgQ29tcG9uZW50IHtcbiAgICAvKipcbiAgICAgKiBDcmVhdGVzIGEgbmV3IExpZ2h0Q29tcG9uZW50IGluc3RhbmNlLlxuICAgICAqXG4gICAgICogQHBhcmFtIHtpbXBvcnQoJy4vc3lzdGVtLmpzJykuTGlnaHRDb21wb25lbnRTeXN0ZW19IHN5c3RlbSAtIFRoZSBDb21wb25lbnRTeXN0ZW0gdGhhdFxuICAgICAqIGNyZWF0ZWQgdGhpcyBDb21wb25lbnQuXG4gICAgICogQHBhcmFtIHtpbXBvcnQoJy4uLy4uL2VudGl0eS5qcycpLkVudGl0eX0gZW50aXR5IC0gVGhlIEVudGl0eSB0aGF0IHRoaXMgQ29tcG9uZW50IGlzXG4gICAgICogYXR0YWNoZWQgdG8uXG4gICAgICovXG4gICAgY29uc3RydWN0b3Ioc3lzdGVtLCBlbnRpdHkpIHtcbiAgICAgICAgc3VwZXIoc3lzdGVtLCBlbnRpdHkpO1xuXG4gICAgICAgIHRoaXMuX2Nvb2tpZUFzc2V0ID0gbnVsbDtcbiAgICAgICAgdGhpcy5fY29va2llQXNzZXRJZCA9IG51bGw7XG4gICAgICAgIHRoaXMuX2Nvb2tpZUFzc2V0QWRkID0gZmFsc2U7XG4gICAgICAgIHRoaXMuX2Nvb2tpZU1hdHJpeCA9IG51bGw7XG4gICAgfVxuXG4gICAgYWRkTGlnaHRUb0xheWVycygpIHtcbiAgICAgICAgZm9yIChsZXQgaSA9IDA7IGkgPCB0aGlzLmxheWVycy5sZW5ndGg7IGkrKykge1xuICAgICAgICAgICAgY29uc3QgbGF5ZXIgPSB0aGlzLnN5c3RlbS5hcHAuc2NlbmUubGF5ZXJzLmdldExheWVyQnlJZCh0aGlzLmxheWVyc1tpXSk7XG4gICAgICAgICAgICBpZiAobGF5ZXIpIHtcbiAgICAgICAgICAgICAgICBsYXllci5hZGRMaWdodCh0aGlzKTtcbiAgICAgICAgICAgICAgICB0aGlzLmxpZ2h0LmFkZExheWVyKGxheWVyKTtcbiAgICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgIH1cblxuICAgIHJlbW92ZUxpZ2h0RnJvbUxheWVycygpIHtcbiAgICAgICAgZm9yIChsZXQgaSA9IDA7IGkgPCB0aGlzLmxheWVycy5sZW5ndGg7IGkrKykge1xuICAgICAgICAgICAgY29uc3QgbGF5ZXIgPSB0aGlzLnN5c3RlbS5hcHAuc2NlbmUubGF5ZXJzLmdldExheWVyQnlJZCh0aGlzLmxheWVyc1tpXSk7XG4gICAgICAgICAgICBpZiAobGF5ZXIpIHtcbiAgICAgICAgICAgICAgICBsYXllci5yZW1vdmVMaWdodCh0aGlzKTtcbiAgICAgICAgICAgICAgICB0aGlzLmxpZ2h0LnJlbW92ZUxheWVyKGxheWVyKTtcbiAgICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgIH1cblxuICAgIG9uTGF5ZXJzQ2hhbmdlZChvbGRDb21wLCBuZXdDb21wKSB7XG4gICAgICAgIGlmICh0aGlzLmVuYWJsZWQgJiYgdGhpcy5lbnRpdHkuZW5hYmxlZCkge1xuICAgICAgICAgICAgdGhpcy5hZGRMaWdodFRvTGF5ZXJzKCk7XG4gICAgICAgIH1cbiAgICAgICAgb2xkQ29tcC5vZmYoJ2FkZCcsIHRoaXMub25MYXllckFkZGVkLCB0aGlzKTtcbiAgICAgICAgb2xkQ29tcC5vZmYoJ3JlbW92ZScsIHRoaXMub25MYXllclJlbW92ZWQsIHRoaXMpO1xuICAgICAgICBuZXdDb21wLm9uKCdhZGQnLCB0aGlzLm9uTGF5ZXJBZGRlZCwgdGhpcyk7XG4gICAgICAgIG5ld0NvbXAub24oJ3JlbW92ZScsIHRoaXMub25MYXllclJlbW92ZWQsIHRoaXMpO1xuICAgIH1cblxuICAgIG9uTGF5ZXJBZGRlZChsYXllcikge1xuICAgICAgICBjb25zdCBpbmRleCA9IHRoaXMubGF5ZXJzLmluZGV4T2YobGF5ZXIuaWQpO1xuICAgICAgICBpZiAoaW5kZXggPj0gMCAmJiB0aGlzLmVuYWJsZWQgJiYgdGhpcy5lbnRpdHkuZW5hYmxlZCkge1xuICAgICAgICAgICAgbGF5ZXIuYWRkTGlnaHQodGhpcyk7XG4gICAgICAgICAgICB0aGlzLmxpZ2h0LmFkZExheWVyKGxheWVyKTtcbiAgICAgICAgfVxuICAgIH1cblxuICAgIG9uTGF5ZXJSZW1vdmVkKGxheWVyKSB7XG4gICAgICAgIGNvbnN0IGluZGV4ID0gdGhpcy5sYXllcnMuaW5kZXhPZihsYXllci5pZCk7XG4gICAgICAgIGlmIChpbmRleCA+PSAwKSB7XG4gICAgICAgICAgICBsYXllci5yZW1vdmVMaWdodCh0aGlzKTtcbiAgICAgICAgICAgIHRoaXMubGlnaHQucmVtb3ZlTGF5ZXIobGF5ZXIpO1xuICAgICAgICB9XG4gICAgfVxuXG4gICAgcmVmcmVzaFByb3BlcnRpZXMoKSB7XG4gICAgICAgIGZvciAobGV0IGkgPSAwOyBpIDwgX2xpZ2h0UHJvcHMubGVuZ3RoOyBpKyspIHtcbiAgICAgICAgICAgIGNvbnN0IG5hbWUgPSBfbGlnaHRQcm9wc1tpXTtcblxuICAgICAgICAgICAgLyogZXNsaW50LWRpc2FibGUgbm8tc2VsZi1hc3NpZ24gKi9cbiAgICAgICAgICAgIHRoaXNbbmFtZV0gPSB0aGlzW25hbWVdO1xuICAgICAgICAgICAgLyogZXNsaW50LWVuYWJsZSBuby1zZWxmLWFzc2lnbiAqL1xuICAgICAgICB9XG4gICAgICAgIGlmICh0aGlzLmVuYWJsZWQgJiYgdGhpcy5lbnRpdHkuZW5hYmxlZClcbiAgICAgICAgICAgIHRoaXMub25FbmFibGUoKTtcbiAgICB9XG5cbiAgICBvbkNvb2tpZUFzc2V0U2V0KCkge1xuICAgICAgICBsZXQgZm9yY2VMb2FkID0gZmFsc2U7XG5cbiAgICAgICAgaWYgKHRoaXMuX2Nvb2tpZUFzc2V0LnR5cGUgPT09ICdjdWJlbWFwJyAmJiAhdGhpcy5fY29va2llQXNzZXQubG9hZEZhY2VzKSB7XG4gICAgICAgICAgICB0aGlzLl9jb29raWVBc3NldC5sb2FkRmFjZXMgPSB0cnVlO1xuICAgICAgICAgICAgZm9yY2VMb2FkID0gdHJ1ZTtcbiAgICAgICAgfVxuXG4gICAgICAgIGlmICghdGhpcy5fY29va2llQXNzZXQucmVzb3VyY2UgfHwgZm9yY2VMb2FkKVxuICAgICAgICAgICAgdGhpcy5zeXN0ZW0uYXBwLmFzc2V0cy5sb2FkKHRoaXMuX2Nvb2tpZUFzc2V0KTtcblxuICAgICAgICBpZiAodGhpcy5fY29va2llQXNzZXQucmVzb3VyY2UpXG4gICAgICAgICAgICB0aGlzLm9uQ29va2llQXNzZXRMb2FkKCk7XG4gICAgfVxuXG4gICAgb25Db29raWVBc3NldEFkZChhc3NldCkge1xuICAgICAgICBpZiAodGhpcy5fY29va2llQXNzZXRJZCAhPT0gYXNzZXQuaWQpXG4gICAgICAgICAgICByZXR1cm47XG5cbiAgICAgICAgdGhpcy5fY29va2llQXNzZXQgPSBhc3NldDtcblxuICAgICAgICBpZiAodGhpcy5saWdodC5lbmFibGVkKVxuICAgICAgICAgICAgdGhpcy5vbkNvb2tpZUFzc2V0U2V0KCk7XG5cbiAgICAgICAgdGhpcy5fY29va2llQXNzZXQub24oJ2xvYWQnLCB0aGlzLm9uQ29va2llQXNzZXRMb2FkLCB0aGlzKTtcbiAgICAgICAgdGhpcy5fY29va2llQXNzZXQub24oJ3JlbW92ZScsIHRoaXMub25Db29raWVBc3NldFJlbW92ZSwgdGhpcyk7XG4gICAgfVxuXG4gICAgb25Db29raWVBc3NldExvYWQoKSB7XG4gICAgICAgIGlmICghdGhpcy5fY29va2llQXNzZXQgfHwgIXRoaXMuX2Nvb2tpZUFzc2V0LnJlc291cmNlKVxuICAgICAgICAgICAgcmV0dXJuO1xuXG4gICAgICAgIHRoaXMuY29va2llID0gdGhpcy5fY29va2llQXNzZXQucmVzb3VyY2U7XG4gICAgfVxuXG4gICAgb25Db29raWVBc3NldFJlbW92ZSgpIHtcbiAgICAgICAgaWYgKCF0aGlzLl9jb29raWVBc3NldElkKVxuICAgICAgICAgICAgcmV0dXJuO1xuXG4gICAgICAgIGlmICh0aGlzLl9jb29raWVBc3NldEFkZCkge1xuICAgICAgICAgICAgdGhpcy5zeXN0ZW0uYXBwLmFzc2V0cy5vZmYoJ2FkZDonICsgdGhpcy5fY29va2llQXNzZXRJZCwgdGhpcy5vbkNvb2tpZUFzc2V0QWRkLCB0aGlzKTtcbiAgICAgICAgICAgIHRoaXMuX2Nvb2tpZUFzc2V0QWRkID0gZmFsc2U7XG4gICAgICAgIH1cblxuICAgICAgICBpZiAodGhpcy5fY29va2llQXNzZXQpIHtcbiAgICAgICAgICAgIHRoaXMuX2Nvb2tpZUFzc2V0Lm9mZignbG9hZCcsIHRoaXMub25Db29raWVBc3NldExvYWQsIHRoaXMpO1xuICAgICAgICAgICAgdGhpcy5fY29va2llQXNzZXQub2ZmKCdyZW1vdmUnLCB0aGlzLm9uQ29va2llQXNzZXRSZW1vdmUsIHRoaXMpO1xuICAgICAgICAgICAgdGhpcy5fY29va2llQXNzZXQgPSBudWxsO1xuICAgICAgICB9XG5cbiAgICAgICAgdGhpcy5jb29raWUgPSBudWxsO1xuICAgIH1cblxuICAgIG9uRW5hYmxlKCkge1xuICAgICAgICB0aGlzLmxpZ2h0LmVuYWJsZWQgPSB0cnVlO1xuXG4gICAgICAgIHRoaXMuc3lzdGVtLmFwcC5zY2VuZS5vbignc2V0OmxheWVycycsIHRoaXMub25MYXllcnNDaGFuZ2VkLCB0aGlzKTtcbiAgICAgICAgaWYgKHRoaXMuc3lzdGVtLmFwcC5zY2VuZS5sYXllcnMpIHtcbiAgICAgICAgICAgIHRoaXMuc3lzdGVtLmFwcC5zY2VuZS5sYXllcnMub24oJ2FkZCcsIHRoaXMub25MYXllckFkZGVkLCB0aGlzKTtcbiAgICAgICAgICAgIHRoaXMuc3lzdGVtLmFwcC5zY2VuZS5sYXllcnMub24oJ3JlbW92ZScsIHRoaXMub25MYXllclJlbW92ZWQsIHRoaXMpO1xuICAgICAgICB9XG5cbiAgICAgICAgaWYgKHRoaXMuZW5hYmxlZCAmJiB0aGlzLmVudGl0eS5lbmFibGVkKSB7XG4gICAgICAgICAgICB0aGlzLmFkZExpZ2h0VG9MYXllcnMoKTtcbiAgICAgICAgfVxuXG4gICAgICAgIGlmICh0aGlzLl9jb29raWVBc3NldCAmJiAhdGhpcy5jb29raWUpXG4gICAgICAgICAgICB0aGlzLm9uQ29va2llQXNzZXRTZXQoKTtcbiAgICB9XG5cbiAgICBvbkRpc2FibGUoKSB7XG4gICAgICAgIHRoaXMubGlnaHQuZW5hYmxlZCA9IGZhbHNlO1xuXG4gICAgICAgIHRoaXMuc3lzdGVtLmFwcC5zY2VuZS5vZmYoJ3NldDpsYXllcnMnLCB0aGlzLm9uTGF5ZXJzQ2hhbmdlZCwgdGhpcyk7XG4gICAgICAgIGlmICh0aGlzLnN5c3RlbS5hcHAuc2NlbmUubGF5ZXJzKSB7XG4gICAgICAgICAgICB0aGlzLnN5c3RlbS5hcHAuc2NlbmUubGF5ZXJzLm9mZignYWRkJywgdGhpcy5vbkxheWVyQWRkZWQsIHRoaXMpO1xuICAgICAgICAgICAgdGhpcy5zeXN0ZW0uYXBwLnNjZW5lLmxheWVycy5vZmYoJ3JlbW92ZScsIHRoaXMub25MYXllclJlbW92ZWQsIHRoaXMpO1xuICAgICAgICB9XG5cbiAgICAgICAgdGhpcy5yZW1vdmVMaWdodEZyb21MYXllcnMoKTtcbiAgICB9XG5cbiAgICBvblJlbW92ZSgpIHtcbiAgICAgICAgLy8gcmVtb3ZlIGZyb20gbGF5ZXJzXG4gICAgICAgIHRoaXMub25EaXNhYmxlKCk7XG5cbiAgICAgICAgLy8gZGVzdHJveSBsaWdodCBub2RlXG4gICAgICAgIHRoaXMubGlnaHQuZGVzdHJveSgpO1xuXG4gICAgICAgIC8vIHJlbW92ZSBjb29raWUgYXNzZXQgZXZlbnRzXG4gICAgICAgIHRoaXMuY29va2llQXNzZXQgPSBudWxsO1xuICAgIH1cblxuICAgIC8qKlxuICAgICAqIFJldHVybnMgYW4gYXJyYXkgb2YgU0hBRE9XVVBEQVRFXyBzZXR0aW5ncyBwZXIgc2hhZG93IGNhc2NhZGUsIG9yIHVuZGVmaW5lZCBpZiBub3QgdXNlZC5cbiAgICAgKlxuICAgICAqIEB0eXBlIHtudW1iZXJbXSB8IG51bGx9XG4gICAgICovXG4gICAgc2V0IHNoYWRvd1VwZGF0ZU92ZXJyaWRlcyh2YWx1ZXMpIHtcbiAgICAgICAgdGhpcy5saWdodC5zaGFkb3dVcGRhdGVPdmVycmlkZXMgPSB2YWx1ZXM7XG4gICAgfVxuXG4gICAgZ2V0IHNoYWRvd1VwZGF0ZU92ZXJyaWRlcygpIHtcbiAgICAgICAgcmV0dXJuIHRoaXMubGlnaHQuc2hhZG93VXBkYXRlT3ZlcnJpZGVzO1xuICAgIH1cblxuICAgIHNldCBwZW51bWJyYVNpemUodmFsdWUpIHtcbiAgICAgICAgdGhpcy5saWdodC5wZW51bWJyYVNpemUgPSB2YWx1ZTtcbiAgICB9XG5cbiAgICBnZXQgcGVudW1icmFTaXplKCkge1xuICAgICAgICByZXR1cm4gdGhpcy5saWdodC5wZW51bWJyYVNpemU7XG4gICAgfVxufVxuXG5mdW5jdGlvbiBfZGVmaW5lUHJvcGVydHkobmFtZSwgZGVmYXVsdFZhbHVlLCBzZXRGdW5jLCBza2lwRXF1YWxzQ2hlY2spIHtcbiAgICBjb25zdCBjID0gTGlnaHRDb21wb25lbnQucHJvdG90eXBlO1xuICAgIF9saWdodFByb3BzLnB1c2gobmFtZSk7XG4gICAgX2xpZ2h0UHJvcHNEZWZhdWx0LnB1c2goZGVmYXVsdFZhbHVlKTtcblxuICAgIE9iamVjdC5kZWZpbmVQcm9wZXJ0eShjLCBuYW1lLCB7XG4gICAgICAgIGdldDogZnVuY3Rpb24gKCkge1xuICAgICAgICAgICAgcmV0dXJuIHRoaXMuZGF0YVtuYW1lXTtcbiAgICAgICAgfSxcbiAgICAgICAgc2V0OiBmdW5jdGlvbiAodmFsdWUpIHtcbiAgICAgICAgICAgIGNvbnN0IGRhdGEgPSB0aGlzLmRhdGE7XG4gICAgICAgICAgICBjb25zdCBvbGRWYWx1ZSA9IGRhdGFbbmFtZV07XG4gICAgICAgICAgICBpZiAoIXNraXBFcXVhbHNDaGVjayAmJiBvbGRWYWx1ZSA9PT0gdmFsdWUpIHJldHVybjtcbiAgICAgICAgICAgIGRhdGFbbmFtZV0gPSB2YWx1ZTtcbiAgICAgICAgICAgIGlmIChzZXRGdW5jKSBzZXRGdW5jLmNhbGwodGhpcywgdmFsdWUsIG9sZFZhbHVlKTtcbiAgICAgICAgfSxcbiAgICAgICAgY29uZmlndXJhYmxlOiB0cnVlXG4gICAgfSk7XG59XG5cbmZ1bmN0aW9uIF9kZWZpbmVQcm9wcygpIHtcbiAgICBfZGVmaW5lUHJvcGVydHkoJ2VuYWJsZWQnLCB0cnVlLCBmdW5jdGlvbiAobmV3VmFsdWUsIG9sZFZhbHVlKSB7XG4gICAgICAgIHRoaXMub25TZXRFbmFibGVkKG51bGwsIG9sZFZhbHVlLCBuZXdWYWx1ZSk7XG4gICAgfSk7XG4gICAgX2RlZmluZVByb3BlcnR5KCdsaWdodCcsIG51bGwpO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgndHlwZScsICdkaXJlY3Rpb25hbCcsIGZ1bmN0aW9uIChuZXdWYWx1ZSwgb2xkVmFsdWUpIHtcbiAgICAgICAgdGhpcy5zeXN0ZW0uY2hhbmdlVHlwZSh0aGlzLCBvbGRWYWx1ZSwgbmV3VmFsdWUpO1xuICAgICAgICAvLyByZWZyZXNoIGxpZ2h0IHByb3BlcnRpZXMgYmVjYXVzZSBjaGFuZ2luZyB0aGUgdHlwZSBkb2VzIG5vdCByZXNldCB0aGVcbiAgICAgICAgLy8gbGlnaHQgcHJvcGVydGllc1xuICAgICAgICB0aGlzLnJlZnJlc2hQcm9wZXJ0aWVzKCk7XG4gICAgfSk7XG4gICAgX2RlZmluZVByb3BlcnR5KCdjb2xvcicsIG5ldyBDb2xvcigxLCAxLCAxKSwgZnVuY3Rpb24gKG5ld1ZhbHVlLCBvbGRWYWx1ZSkge1xuICAgICAgICB0aGlzLmxpZ2h0LnNldENvbG9yKG5ld1ZhbHVlKTtcbiAgICB9LCB0cnVlKTtcbiAgICBfZGVmaW5lUHJvcGVydHkoJ2ludGVuc2l0eScsIDEsIGZ1bmN0aW9uIChuZXdWYWx1ZSwgb2xkVmFsdWUpIHtcbiAgICAgICAgdGhpcy5saWdodC5pbnRlbnNpdHkgPSBuZXdWYWx1ZTtcbiAgICB9KTtcbiAgICBfZGVmaW5lUHJvcGVydHkoJ2x1bWluYW5jZScsIDAsIGZ1bmN0aW9uIChuZXdWYWx1ZSwgb2xkVmFsdWUpIHtcbiAgICAgICAgdGhpcy5saWdodC5sdW1pbmFuY2UgPSBuZXdWYWx1ZTtcbiAgICB9KTtcbiAgICBfZGVmaW5lUHJvcGVydHkoJ3NoYXBlJywgTElHSFRTSEFQRV9QVU5DVFVBTCwgZnVuY3Rpb24gKG5ld1ZhbHVlLCBvbGRWYWx1ZSkge1xuICAgICAgICB0aGlzLmxpZ2h0LnNoYXBlID0gbmV3VmFsdWU7XG4gICAgfSk7XG4gICAgX2RlZmluZVByb3BlcnR5KCdhZmZlY3RTcGVjdWxhcml0eScsIHRydWUsIGZ1bmN0aW9uIChuZXdWYWx1ZSwgb2xkVmFsdWUpIHtcbiAgICAgICAgdGhpcy5saWdodC5hZmZlY3RTcGVjdWxhcml0eSA9IG5ld1ZhbHVlO1xuICAgIH0pO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgnY2FzdFNoYWRvd3MnLCBmYWxzZSwgZnVuY3Rpb24gKG5ld1ZhbHVlLCBvbGRWYWx1ZSkge1xuICAgICAgICB0aGlzLmxpZ2h0LmNhc3RTaGFkb3dzID0gbmV3VmFsdWU7XG4gICAgfSk7XG4gICAgX2RlZmluZVByb3BlcnR5KCdzaGFkb3dEaXN0YW5jZScsIDQwLCBmdW5jdGlvbiAobmV3VmFsdWUsIG9sZFZhbHVlKSB7XG4gICAgICAgIHRoaXMubGlnaHQuc2hhZG93RGlzdGFuY2UgPSBuZXdWYWx1ZTtcbiAgICB9KTtcbiAgICBfZGVmaW5lUHJvcGVydHkoJ3NoYWRvd0ludGVuc2l0eScsIDEsIGZ1bmN0aW9uIChuZXdWYWx1ZSwgb2xkVmFsdWUpIHtcbiAgICAgICAgdGhpcy5saWdodC5zaGFkb3dJbnRlbnNpdHkgPSBuZXdWYWx1ZTtcbiAgICB9KTtcbiAgICBfZGVmaW5lUHJvcGVydHkoJ3NoYWRvd1Jlc29sdXRpb24nLCAxMDI0LCBmdW5jdGlvbiAobmV3VmFsdWUsIG9sZFZhbHVlKSB7XG4gICAgICAgIHRoaXMubGlnaHQuc2hhZG93UmVzb2x1dGlvbiA9IG5ld1ZhbHVlO1xuICAgIH0pO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgnc2hhZG93QmlhcycsIDAuMDUsIGZ1bmN0aW9uIChuZXdWYWx1ZSwgb2xkVmFsdWUpIHtcbiAgICAgICAgdGhpcy5saWdodC5zaGFkb3dCaWFzID0gLTAuMDEgKiBtYXRoLmNsYW1wKG5ld1ZhbHVlLCAwLCAxKTtcbiAgICB9KTtcbiAgICBfZGVmaW5lUHJvcGVydHkoJ251bUNhc2NhZGVzJywgMSwgZnVuY3Rpb24gKG5ld1ZhbHVlLCBvbGRWYWx1ZSkge1xuICAgICAgICB0aGlzLmxpZ2h0Lm51bUNhc2NhZGVzID0gbWF0aC5jbGFtcChNYXRoLmZsb29yKG5ld1ZhbHVlKSwgMSwgNCk7XG4gICAgfSk7XG4gICAgX2RlZmluZVByb3BlcnR5KCdiYWtlTnVtU2FtcGxlcycsIDEsIGZ1bmN0aW9uIChuZXdWYWx1ZSwgb2xkVmFsdWUpIHtcbiAgICAgICAgdGhpcy5saWdodC5iYWtlTnVtU2FtcGxlcyA9IG1hdGguY2xhbXAoTWF0aC5mbG9vcihuZXdWYWx1ZSksIDEsIDI1NSk7XG4gICAgfSk7XG4gICAgX2RlZmluZVByb3BlcnR5KCdiYWtlQXJlYScsIDAsIGZ1bmN0aW9uIChuZXdWYWx1ZSwgb2xkVmFsdWUpIHtcbiAgICAgICAgdGhpcy5saWdodC5iYWtlQXJlYSA9IG1hdGguY2xhbXAobmV3VmFsdWUsIDAsIDE4MCk7XG4gICAgfSk7XG4gICAgX2RlZmluZVByb3BlcnR5KCdjYXNjYWRlRGlzdHJpYnV0aW9uJywgMC41LCBmdW5jdGlvbiAobmV3VmFsdWUsIG9sZFZhbHVlKSB7XG4gICAgICAgIHRoaXMubGlnaHQuY2FzY2FkZURpc3RyaWJ1dGlvbiA9IG1hdGguY2xhbXAobmV3VmFsdWUsIDAsIDEpO1xuICAgIH0pO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgnbm9ybWFsT2Zmc2V0QmlhcycsIDAsIGZ1bmN0aW9uIChuZXdWYWx1ZSwgb2xkVmFsdWUpIHtcbiAgICAgICAgdGhpcy5saWdodC5ub3JtYWxPZmZzZXRCaWFzID0gbWF0aC5jbGFtcChuZXdWYWx1ZSwgMCwgMSk7XG4gICAgfSk7XG4gICAgX2RlZmluZVByb3BlcnR5KCdyYW5nZScsIDEwLCBmdW5jdGlvbiAobmV3VmFsdWUsIG9sZFZhbHVlKSB7XG4gICAgICAgIHRoaXMubGlnaHQuYXR0ZW51YXRpb25FbmQgPSBuZXdWYWx1ZTtcbiAgICB9KTtcbiAgICBfZGVmaW5lUHJvcGVydHkoJ2lubmVyQ29uZUFuZ2xlJywgNDAsIGZ1bmN0aW9uIChuZXdWYWx1ZSwgb2xkVmFsdWUpIHtcbiAgICAgICAgdGhpcy5saWdodC5pbm5lckNvbmVBbmdsZSA9IG5ld1ZhbHVlO1xuICAgIH0pO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgnb3V0ZXJDb25lQW5nbGUnLCA0NSwgZnVuY3Rpb24gKG5ld1ZhbHVlLCBvbGRWYWx1ZSkge1xuICAgICAgICB0aGlzLmxpZ2h0Lm91dGVyQ29uZUFuZ2xlID0gbmV3VmFsdWU7XG4gICAgfSk7XG4gICAgX2RlZmluZVByb3BlcnR5KCdmYWxsb2ZmTW9kZScsIExJR0hURkFMTE9GRl9MSU5FQVIsIGZ1bmN0aW9uIChuZXdWYWx1ZSwgb2xkVmFsdWUpIHtcbiAgICAgICAgdGhpcy5saWdodC5mYWxsb2ZmTW9kZSA9IG5ld1ZhbHVlO1xuICAgIH0pO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgnc2hhZG93VHlwZScsIFNIQURPV19QQ0YzLCBmdW5jdGlvbiAobmV3VmFsdWUsIG9sZFZhbHVlKSB7XG4gICAgICAgIHRoaXMubGlnaHQuc2hhZG93VHlwZSA9IG5ld1ZhbHVlO1xuICAgIH0pO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgndnNtQmx1clNpemUnLCAxMSwgZnVuY3Rpb24gKG5ld1ZhbHVlLCBvbGRWYWx1ZSkge1xuICAgICAgICB0aGlzLmxpZ2h0LnZzbUJsdXJTaXplID0gbmV3VmFsdWU7XG4gICAgfSk7XG4gICAgX2RlZmluZVByb3BlcnR5KCd2c21CbHVyTW9kZScsIEJMVVJfR0FVU1NJQU4sIGZ1bmN0aW9uIChuZXdWYWx1ZSwgb2xkVmFsdWUpIHtcbiAgICAgICAgdGhpcy5saWdodC52c21CbHVyTW9kZSA9IG5ld1ZhbHVlO1xuICAgIH0pO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgndnNtQmlhcycsIDAuMDEgKiAwLjI1LCBmdW5jdGlvbiAobmV3VmFsdWUsIG9sZFZhbHVlKSB7XG4gICAgICAgIHRoaXMubGlnaHQudnNtQmlhcyA9IG1hdGguY2xhbXAobmV3VmFsdWUsIDAsIDEpO1xuICAgIH0pO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgnY29va2llQXNzZXQnLCBudWxsLCBmdW5jdGlvbiAobmV3VmFsdWUsIG9sZFZhbHVlKSB7XG4gICAgICAgIGlmICh0aGlzLl9jb29raWVBc3NldElkICYmICgobmV3VmFsdWUgaW5zdGFuY2VvZiBBc3NldCAmJiBuZXdWYWx1ZS5pZCA9PT0gdGhpcy5fY29va2llQXNzZXRJZCkgfHwgbmV3VmFsdWUgPT09IHRoaXMuX2Nvb2tpZUFzc2V0SWQpKVxuICAgICAgICAgICAgcmV0dXJuO1xuXG4gICAgICAgIHRoaXMub25Db29raWVBc3NldFJlbW92ZSgpO1xuICAgICAgICB0aGlzLl9jb29raWVBc3NldElkID0gbnVsbDtcblxuICAgICAgICBpZiAobmV3VmFsdWUgaW5zdGFuY2VvZiBBc3NldCkge1xuICAgICAgICAgICAgdGhpcy5kYXRhLmNvb2tpZUFzc2V0ID0gbmV3VmFsdWUuaWQ7XG4gICAgICAgICAgICB0aGlzLl9jb29raWVBc3NldElkID0gbmV3VmFsdWUuaWQ7XG4gICAgICAgICAgICB0aGlzLm9uQ29va2llQXNzZXRBZGQobmV3VmFsdWUpO1xuICAgICAgICB9IGVsc2UgaWYgKHR5cGVvZiBuZXdWYWx1ZSA9PT0gJ251bWJlcicpIHtcbiAgICAgICAgICAgIHRoaXMuX2Nvb2tpZUFzc2V0SWQgPSBuZXdWYWx1ZTtcbiAgICAgICAgICAgIGNvbnN0IGFzc2V0ID0gdGhpcy5zeXN0ZW0uYXBwLmFzc2V0cy5nZXQobmV3VmFsdWUpO1xuICAgICAgICAgICAgaWYgKGFzc2V0KSB7XG4gICAgICAgICAgICAgICAgdGhpcy5vbkNvb2tpZUFzc2V0QWRkKGFzc2V0KTtcbiAgICAgICAgICAgIH0gZWxzZSB7XG4gICAgICAgICAgICAgICAgdGhpcy5fY29va2llQXNzZXRBZGQgPSB0cnVlO1xuICAgICAgICAgICAgICAgIHRoaXMuc3lzdGVtLmFwcC5hc3NldHMub24oJ2FkZDonICsgdGhpcy5fY29va2llQXNzZXRJZCwgdGhpcy5vbkNvb2tpZUFzc2V0QWRkLCB0aGlzKTtcbiAgICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgIH0pO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgnY29va2llJywgbnVsbCwgZnVuY3Rpb24gKG5ld1ZhbHVlLCBvbGRWYWx1ZSkge1xuICAgICAgICB0aGlzLmxpZ2h0LmNvb2tpZSA9IG5ld1ZhbHVlO1xuICAgIH0pO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgnY29va2llSW50ZW5zaXR5JywgMSwgZnVuY3Rpb24gKG5ld1ZhbHVlLCBvbGRWYWx1ZSkge1xuICAgICAgICB0aGlzLmxpZ2h0LmNvb2tpZUludGVuc2l0eSA9IG1hdGguY2xhbXAobmV3VmFsdWUsIDAsIDEpO1xuICAgIH0pO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgnY29va2llRmFsbG9mZicsIHRydWUsIGZ1bmN0aW9uIChuZXdWYWx1ZSwgb2xkVmFsdWUpIHtcbiAgICAgICAgdGhpcy5saWdodC5jb29raWVGYWxsb2ZmID0gbmV3VmFsdWU7XG4gICAgfSk7XG4gICAgX2RlZmluZVByb3BlcnR5KCdjb29raWVDaGFubmVsJywgJ3JnYicsIGZ1bmN0aW9uIChuZXdWYWx1ZSwgb2xkVmFsdWUpIHtcbiAgICAgICAgdGhpcy5saWdodC5jb29raWVDaGFubmVsID0gbmV3VmFsdWU7XG4gICAgfSk7XG4gICAgX2RlZmluZVByb3BlcnR5KCdjb29raWVBbmdsZScsIDAsIGZ1bmN0aW9uIChuZXdWYWx1ZSwgb2xkVmFsdWUpIHtcbiAgICAgICAgaWYgKG5ld1ZhbHVlICE9PSAwIHx8IHRoaXMuY29va2llU2NhbGUgIT09IG51bGwpIHtcbiAgICAgICAgICAgIGlmICghdGhpcy5fY29va2llTWF0cml4KSB0aGlzLl9jb29raWVNYXRyaXggPSBuZXcgVmVjNCgpO1xuICAgICAgICAgICAgbGV0IHNjeCA9IDE7XG4gICAgICAgICAgICBsZXQgc2N5ID0gMTtcbiAgICAgICAgICAgIGlmICh0aGlzLmNvb2tpZVNjYWxlKSB7XG4gICAgICAgICAgICAgICAgc2N4ID0gdGhpcy5jb29raWVTY2FsZS54O1xuICAgICAgICAgICAgICAgIHNjeSA9IHRoaXMuY29va2llU2NhbGUueTtcbiAgICAgICAgICAgIH1cbiAgICAgICAgICAgIGNvbnN0IGMgPSBNYXRoLmNvcyhuZXdWYWx1ZSAqIG1hdGguREVHX1RPX1JBRCk7XG4gICAgICAgICAgICBjb25zdCBzID0gTWF0aC5zaW4obmV3VmFsdWUgKiBtYXRoLkRFR19UT19SQUQpO1xuICAgICAgICAgICAgdGhpcy5fY29va2llTWF0cml4LnNldChjIC8gc2N4LCAtcyAvIHNjeCwgcyAvIHNjeSwgYyAvIHNjeSk7XG4gICAgICAgICAgICB0aGlzLmxpZ2h0LmNvb2tpZVRyYW5zZm9ybSA9IHRoaXMuX2Nvb2tpZU1hdHJpeDtcbiAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICAgIHRoaXMubGlnaHQuY29va2llVHJhbnNmb3JtID0gbnVsbDtcbiAgICAgICAgfVxuICAgIH0pO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgnY29va2llU2NhbGUnLCBudWxsLCBmdW5jdGlvbiAobmV3VmFsdWUsIG9sZFZhbHVlKSB7XG4gICAgICAgIGlmIChuZXdWYWx1ZSAhPT0gbnVsbCB8fCB0aGlzLmNvb2tpZUFuZ2xlICE9PSAwKSB7XG4gICAgICAgICAgICBpZiAoIXRoaXMuX2Nvb2tpZU1hdHJpeCkgdGhpcy5fY29va2llTWF0cml4ID0gbmV3IFZlYzQoKTtcbiAgICAgICAgICAgIGNvbnN0IHNjeCA9IG5ld1ZhbHVlLng7XG4gICAgICAgICAgICBjb25zdCBzY3kgPSBuZXdWYWx1ZS55O1xuICAgICAgICAgICAgY29uc3QgYyA9IE1hdGguY29zKHRoaXMuY29va2llQW5nbGUgKiBtYXRoLkRFR19UT19SQUQpO1xuICAgICAgICAgICAgY29uc3QgcyA9IE1hdGguc2luKHRoaXMuY29va2llQW5nbGUgKiBtYXRoLkRFR19UT19SQUQpO1xuICAgICAgICAgICAgdGhpcy5fY29va2llTWF0cml4LnNldChjIC8gc2N4LCAtcyAvIHNjeCwgcyAvIHNjeSwgYyAvIHNjeSk7XG4gICAgICAgICAgICB0aGlzLmxpZ2h0LmNvb2tpZVRyYW5zZm9ybSA9IHRoaXMuX2Nvb2tpZU1hdHJpeDtcbiAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICAgIHRoaXMubGlnaHQuY29va2llVHJhbnNmb3JtID0gbnVsbDtcbiAgICAgICAgfVxuICAgIH0sIHRydWUpO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgnY29va2llT2Zmc2V0JywgbnVsbCwgZnVuY3Rpb24gKG5ld1ZhbHVlLCBvbGRWYWx1ZSkge1xuICAgICAgICB0aGlzLmxpZ2h0LmNvb2tpZU9mZnNldCA9IG5ld1ZhbHVlO1xuICAgIH0sIHRydWUpO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgnc2hhZG93VXBkYXRlTW9kZScsIFNIQURPV1VQREFURV9SRUFMVElNRSwgZnVuY3Rpb24gKG5ld1ZhbHVlLCBvbGRWYWx1ZSkge1xuICAgICAgICB0aGlzLmxpZ2h0LnNoYWRvd1VwZGF0ZU1vZGUgPSBuZXdWYWx1ZTtcbiAgICB9LCB0cnVlKTtcbiAgICBfZGVmaW5lUHJvcGVydHkoJ21hc2snLCAxLCBmdW5jdGlvbiAobmV3VmFsdWUsIG9sZFZhbHVlKSB7XG4gICAgICAgIHRoaXMubGlnaHQubWFzayA9IG5ld1ZhbHVlO1xuICAgIH0pO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgnYWZmZWN0RHluYW1pYycsIHRydWUsIGZ1bmN0aW9uIChuZXdWYWx1ZSwgb2xkVmFsdWUpIHtcbiAgICAgICAgaWYgKG5ld1ZhbHVlKSB7XG4gICAgICAgICAgICB0aGlzLmxpZ2h0Lm1hc2sgfD0gTUFTS19BRkZFQ1RfRFlOQU1JQztcbiAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICAgIHRoaXMubGlnaHQubWFzayAmPSB+TUFTS19BRkZFQ1RfRFlOQU1JQztcbiAgICAgICAgfVxuICAgICAgICB0aGlzLmxpZ2h0LmxheWVyc0RpcnR5KCk7XG4gICAgfSk7XG4gICAgX2RlZmluZVByb3BlcnR5KCdhZmZlY3RMaWdodG1hcHBlZCcsIGZhbHNlLCBmdW5jdGlvbiAobmV3VmFsdWUsIG9sZFZhbHVlKSB7XG4gICAgICAgIGlmIChuZXdWYWx1ZSkge1xuICAgICAgICAgICAgdGhpcy5saWdodC5tYXNrIHw9IE1BU0tfQUZGRUNUX0xJR0hUTUFQUEVEO1xuICAgICAgICAgICAgaWYgKHRoaXMuYmFrZSkgdGhpcy5saWdodC5tYXNrICY9IH5NQVNLX0JBS0U7XG4gICAgICAgIH0gZWxzZSB7XG4gICAgICAgICAgICB0aGlzLmxpZ2h0Lm1hc2sgJj0gfk1BU0tfQUZGRUNUX0xJR0hUTUFQUEVEO1xuICAgICAgICAgICAgaWYgKHRoaXMuYmFrZSkgdGhpcy5saWdodC5tYXNrIHw9IE1BU0tfQkFLRTtcbiAgICAgICAgfVxuICAgIH0pO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgnYmFrZScsIGZhbHNlLCBmdW5jdGlvbiAobmV3VmFsdWUsIG9sZFZhbHVlKSB7XG4gICAgICAgIGlmIChuZXdWYWx1ZSkge1xuICAgICAgICAgICAgdGhpcy5saWdodC5tYXNrIHw9IE1BU0tfQkFLRTtcbiAgICAgICAgICAgIGlmICh0aGlzLmFmZmVjdExpZ2h0bWFwcGVkKSB0aGlzLmxpZ2h0Lm1hc2sgJj0gfk1BU0tfQUZGRUNUX0xJR0hUTUFQUEVEO1xuICAgICAgICB9IGVsc2Uge1xuICAgICAgICAgICAgdGhpcy5saWdodC5tYXNrICY9IH5NQVNLX0JBS0U7XG4gICAgICAgICAgICBpZiAodGhpcy5hZmZlY3RMaWdodG1hcHBlZCkgdGhpcy5saWdodC5tYXNrIHw9IE1BU0tfQUZGRUNUX0xJR0hUTUFQUEVEO1xuICAgICAgICB9XG4gICAgICAgIHRoaXMubGlnaHQubGF5ZXJzRGlydHkoKTtcbiAgICB9KTtcbiAgICBfZGVmaW5lUHJvcGVydHkoJ2Jha2VEaXInLCB0cnVlLCBmdW5jdGlvbiAobmV3VmFsdWUsIG9sZFZhbHVlKSB7XG4gICAgICAgIHRoaXMubGlnaHQuYmFrZURpciA9IG5ld1ZhbHVlO1xuICAgIH0pO1xuICAgIF9kZWZpbmVQcm9wZXJ0eSgnaXNTdGF0aWMnLCBmYWxzZSwgZnVuY3Rpb24gKG5ld1ZhbHVlLCBvbGRWYWx1ZSkge1xuICAgICAgICB0aGlzLmxpZ2h0LmlzU3RhdGljID0gbmV3VmFsdWU7XG4gICAgfSk7XG4gICAgX2RlZmluZVByb3BlcnR5KCdsYXllcnMnLCBbTEFZRVJJRF9XT1JMRF0sIGZ1bmN0aW9uIChuZXdWYWx1ZSwgb2xkVmFsdWUpIHtcbiAgICAgICAgZm9yIChsZXQgaSA9IDA7IGkgPCBvbGRWYWx1ZS5sZW5ndGg7IGkrKykge1xuICAgICAgICAgICAgY29uc3QgbGF5ZXIgPSB0aGlzLnN5c3RlbS5hcHAuc2NlbmUubGF5ZXJzLmdldExheWVyQnlJZChvbGRWYWx1ZVtpXSk7XG4gICAgICAgICAgICBpZiAoIWxheWVyKSBjb250aW51ZTtcbiAgICAgICAgICAgIGxheWVyLnJlbW92ZUxpZ2h0KHRoaXMpO1xuICAgICAgICAgICAgdGhpcy5saWdodC5yZW1vdmVMYXllcihsYXllcik7XG4gICAgICAgIH1cbiAgICAgICAgZm9yIChsZXQgaSA9IDA7IGkgPCBuZXdWYWx1ZS5sZW5ndGg7IGkrKykge1xuICAgICAgICAgICAgY29uc3QgbGF5ZXIgPSB0aGlzLnN5c3RlbS5hcHAuc2NlbmUubGF5ZXJzLmdldExheWVyQnlJZChuZXdWYWx1ZVtpXSk7XG4gICAgICAgICAgICBpZiAoIWxheWVyKSBjb250aW51ZTtcbiAgICAgICAgICAgIGlmICh0aGlzLmVuYWJsZWQgJiYgdGhpcy5lbnRpdHkuZW5hYmxlZCkge1xuICAgICAgICAgICAgICAgIGxheWVyLmFkZExpZ2h0KHRoaXMpO1xuICAgICAgICAgICAgICAgIHRoaXMubGlnaHQuYWRkTGF5ZXIobGF5ZXIpO1xuICAgICAgICAgICAgfVxuICAgICAgICB9XG4gICAgfSk7XG5cbiAgICBfbGlnaHRQcm9wcy5wdXNoKFwicGVudW1icmFTaXplXCIpO1xuICAgIF9saWdodFByb3BzRGVmYXVsdC5wdXNoKDEpO1xufVxuXG5fZGVmaW5lUHJvcHMoKTtcblxuZXhwb3J0IHsgX2xpZ2h0UHJvcHMsIF9saWdodFByb3BzRGVmYXVsdCwgTGlnaHRDb21wb25lbnQgfTtcbiJdLCJuYW1lcyI6WyJfbGlnaHRQcm9wcyIsIl9saWdodFByb3BzRGVmYXVsdCIsIkxpZ2h0Q29tcG9uZW50IiwiQ29tcG9uZW50IiwiY29uc3RydWN0b3IiLCJzeXN0ZW0iLCJlbnRpdHkiLCJfY29va2llQXNzZXQiLCJfY29va2llQXNzZXRJZCIsIl9jb29raWVBc3NldEFkZCIsIl9jb29raWVNYXRyaXgiLCJhZGRMaWdodFRvTGF5ZXJzIiwiaSIsImxheWVycyIsImxlbmd0aCIsImxheWVyIiwiYXBwIiwic2NlbmUiLCJnZXRMYXllckJ5SWQiLCJhZGRMaWdodCIsImxpZ2h0IiwiYWRkTGF5ZXIiLCJyZW1vdmVMaWdodEZyb21MYXllcnMiLCJyZW1vdmVMaWdodCIsInJlbW92ZUxheWVyIiwib25MYXllcnNDaGFuZ2VkIiwib2xkQ29tcCIsIm5ld0NvbXAiLCJlbmFibGVkIiwib2ZmIiwib25MYXllckFkZGVkIiwib25MYXllclJlbW92ZWQiLCJvbiIsImluZGV4IiwiaW5kZXhPZiIsImlkIiwicmVmcmVzaFByb3BlcnRpZXMiLCJuYW1lIiwib25FbmFibGUiLCJvbkNvb2tpZUFzc2V0U2V0IiwiZm9yY2VMb2FkIiwidHlwZSIsImxvYWRGYWNlcyIsInJlc291cmNlIiwiYXNzZXRzIiwibG9hZCIsIm9uQ29va2llQXNzZXRMb2FkIiwib25Db29raWVBc3NldEFkZCIsImFzc2V0Iiwib25Db29raWVBc3NldFJlbW92ZSIsImNvb2tpZSIsIm9uRGlzYWJsZSIsIm9uUmVtb3ZlIiwiZGVzdHJveSIsImNvb2tpZUFzc2V0Iiwic2hhZG93VXBkYXRlT3ZlcnJpZGVzIiwidmFsdWVzIiwicGVudW1icmFTaXplIiwidmFsdWUiLCJfZGVmaW5lUHJvcGVydHkiLCJkZWZhdWx0VmFsdWUiLCJzZXRGdW5jIiwic2tpcEVxdWFsc0NoZWNrIiwiYyIsInByb3RvdHlwZSIsInB1c2giLCJPYmplY3QiLCJkZWZpbmVQcm9wZXJ0eSIsImdldCIsImRhdGEiLCJzZXQiLCJvbGRWYWx1ZSIsImNhbGwiLCJjb25maWd1cmFibGUiLCJfZGVmaW5lUHJvcHMiLCJuZXdWYWx1ZSIsIm9uU2V0RW5hYmxlZCIsImNoYW5nZVR5cGUiLCJDb2xvciIsInNldENvbG9yIiwiaW50ZW5zaXR5IiwibHVtaW5hbmNlIiwiTElHSFRTSEFQRV9QVU5DVFVBTCIsInNoYXBlIiwiYWZmZWN0U3BlY3VsYXJpdHkiLCJjYXN0U2hhZG93cyIsInNoYWRvd0Rpc3RhbmNlIiwic2hhZG93SW50ZW5zaXR5Iiwic2hhZG93UmVzb2x1dGlvbiIsInNoYWRvd0JpYXMiLCJtYXRoIiwiY2xhbXAiLCJudW1DYXNjYWRlcyIsIk1hdGgiLCJmbG9vciIsImJha2VOdW1TYW1wbGVzIiwiYmFrZUFyZWEiLCJjYXNjYWRlRGlzdHJpYnV0aW9uIiwibm9ybWFsT2Zmc2V0QmlhcyIsImF0dGVudWF0aW9uRW5kIiwiaW5uZXJDb25lQW5nbGUiLCJvdXRlckNvbmVBbmdsZSIsIkxJR0hURkFMTE9GRl9MSU5FQVIiLCJmYWxsb2ZmTW9kZSIsIlNIQURPV19QQ0YzIiwic2hhZG93VHlwZSIsInZzbUJsdXJTaXplIiwiQkxVUl9HQVVTU0lBTiIsInZzbUJsdXJNb2RlIiwidnNtQmlhcyIsIkFzc2V0IiwiY29va2llSW50ZW5zaXR5IiwiY29va2llRmFsbG9mZiIsImNvb2tpZUNoYW5uZWwiLCJjb29raWVTY2FsZSIsIlZlYzQiLCJzY3giLCJzY3kiLCJ4IiwieSIsImNvcyIsIkRFR19UT19SQUQiLCJzIiwic2luIiwiY29va2llVHJhbnNmb3JtIiwiY29va2llQW5nbGUiLCJjb29raWVPZmZzZXQiLCJTSEFET1dVUERBVEVfUkVBTFRJTUUiLCJzaGFkb3dVcGRhdGVNb2RlIiwibWFzayIsIk1BU0tfQUZGRUNUX0RZTkFNSUMiLCJsYXllcnNEaXJ0eSIsIk1BU0tfQUZGRUNUX0xJR0hUTUFQUEVEIiwiYmFrZSIsIk1BU0tfQkFLRSIsImFmZmVjdExpZ2h0bWFwcGVkIiwiYmFrZURpciIsImlzU3RhdGljIiwiTEFZRVJJRF9XT1JMRCJdLCJtYXBwaW5ncyI6Ijs7Ozs7OztBQWtCTUEsTUFBQUEsV0FBVyxHQUFHLEdBQUU7QUFDaEJDLE1BQUFBLGtCQUFrQixHQUFHLEdBQUU7O0FBRTdCO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBLE1BQU1DLGNBQWMsU0FBU0MsU0FBUyxDQUFDO0FBQ25DO0FBQ0o7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDSUMsRUFBQUEsV0FBV0EsQ0FBQ0MsTUFBTSxFQUFFQyxNQUFNLEVBQUU7QUFDeEIsSUFBQSxLQUFLLENBQUNELE1BQU0sRUFBRUMsTUFBTSxDQUFDLENBQUE7SUFFckIsSUFBSSxDQUFDQyxZQUFZLEdBQUcsSUFBSSxDQUFBO0lBQ3hCLElBQUksQ0FBQ0MsY0FBYyxHQUFHLElBQUksQ0FBQTtJQUMxQixJQUFJLENBQUNDLGVBQWUsR0FBRyxLQUFLLENBQUE7SUFDNUIsSUFBSSxDQUFDQyxhQUFhLEdBQUcsSUFBSSxDQUFBO0FBQzdCLEdBQUE7QUFFQUMsRUFBQUEsZ0JBQWdCQSxHQUFHO0FBQ2YsSUFBQSxLQUFLLElBQUlDLENBQUMsR0FBRyxDQUFDLEVBQUVBLENBQUMsR0FBRyxJQUFJLENBQUNDLE1BQU0sQ0FBQ0MsTUFBTSxFQUFFRixDQUFDLEVBQUUsRUFBRTtNQUN6QyxNQUFNRyxLQUFLLEdBQUcsSUFBSSxDQUFDVixNQUFNLENBQUNXLEdBQUcsQ0FBQ0MsS0FBSyxDQUFDSixNQUFNLENBQUNLLFlBQVksQ0FBQyxJQUFJLENBQUNMLE1BQU0sQ0FBQ0QsQ0FBQyxDQUFDLENBQUMsQ0FBQTtBQUN2RSxNQUFBLElBQUlHLEtBQUssRUFBRTtBQUNQQSxRQUFBQSxLQUFLLENBQUNJLFFBQVEsQ0FBQyxJQUFJLENBQUMsQ0FBQTtBQUNwQixRQUFBLElBQUksQ0FBQ0MsS0FBSyxDQUFDQyxRQUFRLENBQUNOLEtBQUssQ0FBQyxDQUFBO0FBQzlCLE9BQUE7QUFDSixLQUFBO0FBQ0osR0FBQTtBQUVBTyxFQUFBQSxxQkFBcUJBLEdBQUc7QUFDcEIsSUFBQSxLQUFLLElBQUlWLENBQUMsR0FBRyxDQUFDLEVBQUVBLENBQUMsR0FBRyxJQUFJLENBQUNDLE1BQU0sQ0FBQ0MsTUFBTSxFQUFFRixDQUFDLEVBQUUsRUFBRTtNQUN6QyxNQUFNRyxLQUFLLEdBQUcsSUFBSSxDQUFDVixNQUFNLENBQUNXLEdBQUcsQ0FBQ0MsS0FBSyxDQUFDSixNQUFNLENBQUNLLFlBQVksQ0FBQyxJQUFJLENBQUNMLE1BQU0sQ0FBQ0QsQ0FBQyxDQUFDLENBQUMsQ0FBQTtBQUN2RSxNQUFBLElBQUlHLEtBQUssRUFBRTtBQUNQQSxRQUFBQSxLQUFLLENBQUNRLFdBQVcsQ0FBQyxJQUFJLENBQUMsQ0FBQTtBQUN2QixRQUFBLElBQUksQ0FBQ0gsS0FBSyxDQUFDSSxXQUFXLENBQUNULEtBQUssQ0FBQyxDQUFBO0FBQ2pDLE9BQUE7QUFDSixLQUFBO0FBQ0osR0FBQTtBQUVBVSxFQUFBQSxlQUFlQSxDQUFDQyxPQUFPLEVBQUVDLE9BQU8sRUFBRTtJQUM5QixJQUFJLElBQUksQ0FBQ0MsT0FBTyxJQUFJLElBQUksQ0FBQ3RCLE1BQU0sQ0FBQ3NCLE9BQU8sRUFBRTtNQUNyQyxJQUFJLENBQUNqQixnQkFBZ0IsRUFBRSxDQUFBO0FBQzNCLEtBQUE7SUFDQWUsT0FBTyxDQUFDRyxHQUFHLENBQUMsS0FBSyxFQUFFLElBQUksQ0FBQ0MsWUFBWSxFQUFFLElBQUksQ0FBQyxDQUFBO0lBQzNDSixPQUFPLENBQUNHLEdBQUcsQ0FBQyxRQUFRLEVBQUUsSUFBSSxDQUFDRSxjQUFjLEVBQUUsSUFBSSxDQUFDLENBQUE7SUFDaERKLE9BQU8sQ0FBQ0ssRUFBRSxDQUFDLEtBQUssRUFBRSxJQUFJLENBQUNGLFlBQVksRUFBRSxJQUFJLENBQUMsQ0FBQTtJQUMxQ0gsT0FBTyxDQUFDSyxFQUFFLENBQUMsUUFBUSxFQUFFLElBQUksQ0FBQ0QsY0FBYyxFQUFFLElBQUksQ0FBQyxDQUFBO0FBQ25ELEdBQUE7RUFFQUQsWUFBWUEsQ0FBQ2YsS0FBSyxFQUFFO0lBQ2hCLE1BQU1rQixLQUFLLEdBQUcsSUFBSSxDQUFDcEIsTUFBTSxDQUFDcUIsT0FBTyxDQUFDbkIsS0FBSyxDQUFDb0IsRUFBRSxDQUFDLENBQUE7QUFDM0MsSUFBQSxJQUFJRixLQUFLLElBQUksQ0FBQyxJQUFJLElBQUksQ0FBQ0wsT0FBTyxJQUFJLElBQUksQ0FBQ3RCLE1BQU0sQ0FBQ3NCLE9BQU8sRUFBRTtBQUNuRGIsTUFBQUEsS0FBSyxDQUFDSSxRQUFRLENBQUMsSUFBSSxDQUFDLENBQUE7QUFDcEIsTUFBQSxJQUFJLENBQUNDLEtBQUssQ0FBQ0MsUUFBUSxDQUFDTixLQUFLLENBQUMsQ0FBQTtBQUM5QixLQUFBO0FBQ0osR0FBQTtFQUVBZ0IsY0FBY0EsQ0FBQ2hCLEtBQUssRUFBRTtJQUNsQixNQUFNa0IsS0FBSyxHQUFHLElBQUksQ0FBQ3BCLE1BQU0sQ0FBQ3FCLE9BQU8sQ0FBQ25CLEtBQUssQ0FBQ29CLEVBQUUsQ0FBQyxDQUFBO0lBQzNDLElBQUlGLEtBQUssSUFBSSxDQUFDLEVBQUU7QUFDWmxCLE1BQUFBLEtBQUssQ0FBQ1EsV0FBVyxDQUFDLElBQUksQ0FBQyxDQUFBO0FBQ3ZCLE1BQUEsSUFBSSxDQUFDSCxLQUFLLENBQUNJLFdBQVcsQ0FBQ1QsS0FBSyxDQUFDLENBQUE7QUFDakMsS0FBQTtBQUNKLEdBQUE7QUFFQXFCLEVBQUFBLGlCQUFpQkEsR0FBRztBQUNoQixJQUFBLEtBQUssSUFBSXhCLENBQUMsR0FBRyxDQUFDLEVBQUVBLENBQUMsR0FBR1osV0FBVyxDQUFDYyxNQUFNLEVBQUVGLENBQUMsRUFBRSxFQUFFO0FBQ3pDLE1BQUEsTUFBTXlCLElBQUksR0FBR3JDLFdBQVcsQ0FBQ1ksQ0FBQyxDQUFDLENBQUE7O0FBRTNCO0FBQ0EsTUFBQSxJQUFJLENBQUN5QixJQUFJLENBQUMsR0FBRyxJQUFJLENBQUNBLElBQUksQ0FBQyxDQUFBO0FBQ3ZCO0FBQ0osS0FBQTs7QUFDQSxJQUFBLElBQUksSUFBSSxDQUFDVCxPQUFPLElBQUksSUFBSSxDQUFDdEIsTUFBTSxDQUFDc0IsT0FBTyxFQUNuQyxJQUFJLENBQUNVLFFBQVEsRUFBRSxDQUFBO0FBQ3ZCLEdBQUE7QUFFQUMsRUFBQUEsZ0JBQWdCQSxHQUFHO0lBQ2YsSUFBSUMsU0FBUyxHQUFHLEtBQUssQ0FBQTtBQUVyQixJQUFBLElBQUksSUFBSSxDQUFDakMsWUFBWSxDQUFDa0MsSUFBSSxLQUFLLFNBQVMsSUFBSSxDQUFDLElBQUksQ0FBQ2xDLFlBQVksQ0FBQ21DLFNBQVMsRUFBRTtBQUN0RSxNQUFBLElBQUksQ0FBQ25DLFlBQVksQ0FBQ21DLFNBQVMsR0FBRyxJQUFJLENBQUE7QUFDbENGLE1BQUFBLFNBQVMsR0FBRyxJQUFJLENBQUE7QUFDcEIsS0FBQTtJQUVBLElBQUksQ0FBQyxJQUFJLENBQUNqQyxZQUFZLENBQUNvQyxRQUFRLElBQUlILFNBQVMsRUFDeEMsSUFBSSxDQUFDbkMsTUFBTSxDQUFDVyxHQUFHLENBQUM0QixNQUFNLENBQUNDLElBQUksQ0FBQyxJQUFJLENBQUN0QyxZQUFZLENBQUMsQ0FBQTtJQUVsRCxJQUFJLElBQUksQ0FBQ0EsWUFBWSxDQUFDb0MsUUFBUSxFQUMxQixJQUFJLENBQUNHLGlCQUFpQixFQUFFLENBQUE7QUFDaEMsR0FBQTtFQUVBQyxnQkFBZ0JBLENBQUNDLEtBQUssRUFBRTtBQUNwQixJQUFBLElBQUksSUFBSSxDQUFDeEMsY0FBYyxLQUFLd0MsS0FBSyxDQUFDYixFQUFFLEVBQ2hDLE9BQUE7SUFFSixJQUFJLENBQUM1QixZQUFZLEdBQUd5QyxLQUFLLENBQUE7SUFFekIsSUFBSSxJQUFJLENBQUM1QixLQUFLLENBQUNRLE9BQU8sRUFDbEIsSUFBSSxDQUFDVyxnQkFBZ0IsRUFBRSxDQUFBO0FBRTNCLElBQUEsSUFBSSxDQUFDaEMsWUFBWSxDQUFDeUIsRUFBRSxDQUFDLE1BQU0sRUFBRSxJQUFJLENBQUNjLGlCQUFpQixFQUFFLElBQUksQ0FBQyxDQUFBO0FBQzFELElBQUEsSUFBSSxDQUFDdkMsWUFBWSxDQUFDeUIsRUFBRSxDQUFDLFFBQVEsRUFBRSxJQUFJLENBQUNpQixtQkFBbUIsRUFBRSxJQUFJLENBQUMsQ0FBQTtBQUNsRSxHQUFBO0FBRUFILEVBQUFBLGlCQUFpQkEsR0FBRztJQUNoQixJQUFJLENBQUMsSUFBSSxDQUFDdkMsWUFBWSxJQUFJLENBQUMsSUFBSSxDQUFDQSxZQUFZLENBQUNvQyxRQUFRLEVBQ2pELE9BQUE7QUFFSixJQUFBLElBQUksQ0FBQ08sTUFBTSxHQUFHLElBQUksQ0FBQzNDLFlBQVksQ0FBQ29DLFFBQVEsQ0FBQTtBQUM1QyxHQUFBO0FBRUFNLEVBQUFBLG1CQUFtQkEsR0FBRztBQUNsQixJQUFBLElBQUksQ0FBQyxJQUFJLENBQUN6QyxjQUFjLEVBQ3BCLE9BQUE7SUFFSixJQUFJLElBQUksQ0FBQ0MsZUFBZSxFQUFFO01BQ3RCLElBQUksQ0FBQ0osTUFBTSxDQUFDVyxHQUFHLENBQUM0QixNQUFNLENBQUNmLEdBQUcsQ0FBQyxNQUFNLEdBQUcsSUFBSSxDQUFDckIsY0FBYyxFQUFFLElBQUksQ0FBQ3VDLGdCQUFnQixFQUFFLElBQUksQ0FBQyxDQUFBO01BQ3JGLElBQUksQ0FBQ3RDLGVBQWUsR0FBRyxLQUFLLENBQUE7QUFDaEMsS0FBQTtJQUVBLElBQUksSUFBSSxDQUFDRixZQUFZLEVBQUU7QUFDbkIsTUFBQSxJQUFJLENBQUNBLFlBQVksQ0FBQ3NCLEdBQUcsQ0FBQyxNQUFNLEVBQUUsSUFBSSxDQUFDaUIsaUJBQWlCLEVBQUUsSUFBSSxDQUFDLENBQUE7QUFDM0QsTUFBQSxJQUFJLENBQUN2QyxZQUFZLENBQUNzQixHQUFHLENBQUMsUUFBUSxFQUFFLElBQUksQ0FBQ29CLG1CQUFtQixFQUFFLElBQUksQ0FBQyxDQUFBO01BQy9ELElBQUksQ0FBQzFDLFlBQVksR0FBRyxJQUFJLENBQUE7QUFDNUIsS0FBQTtJQUVBLElBQUksQ0FBQzJDLE1BQU0sR0FBRyxJQUFJLENBQUE7QUFDdEIsR0FBQTtBQUVBWixFQUFBQSxRQUFRQSxHQUFHO0FBQ1AsSUFBQSxJQUFJLENBQUNsQixLQUFLLENBQUNRLE9BQU8sR0FBRyxJQUFJLENBQUE7QUFFekIsSUFBQSxJQUFJLENBQUN2QixNQUFNLENBQUNXLEdBQUcsQ0FBQ0MsS0FBSyxDQUFDZSxFQUFFLENBQUMsWUFBWSxFQUFFLElBQUksQ0FBQ1AsZUFBZSxFQUFFLElBQUksQ0FBQyxDQUFBO0lBQ2xFLElBQUksSUFBSSxDQUFDcEIsTUFBTSxDQUFDVyxHQUFHLENBQUNDLEtBQUssQ0FBQ0osTUFBTSxFQUFFO0FBQzlCLE1BQUEsSUFBSSxDQUFDUixNQUFNLENBQUNXLEdBQUcsQ0FBQ0MsS0FBSyxDQUFDSixNQUFNLENBQUNtQixFQUFFLENBQUMsS0FBSyxFQUFFLElBQUksQ0FBQ0YsWUFBWSxFQUFFLElBQUksQ0FBQyxDQUFBO0FBQy9ELE1BQUEsSUFBSSxDQUFDekIsTUFBTSxDQUFDVyxHQUFHLENBQUNDLEtBQUssQ0FBQ0osTUFBTSxDQUFDbUIsRUFBRSxDQUFDLFFBQVEsRUFBRSxJQUFJLENBQUNELGNBQWMsRUFBRSxJQUFJLENBQUMsQ0FBQTtBQUN4RSxLQUFBO0lBRUEsSUFBSSxJQUFJLENBQUNILE9BQU8sSUFBSSxJQUFJLENBQUN0QixNQUFNLENBQUNzQixPQUFPLEVBQUU7TUFDckMsSUFBSSxDQUFDakIsZ0JBQWdCLEVBQUUsQ0FBQTtBQUMzQixLQUFBO0FBRUEsSUFBQSxJQUFJLElBQUksQ0FBQ0osWUFBWSxJQUFJLENBQUMsSUFBSSxDQUFDMkMsTUFBTSxFQUNqQyxJQUFJLENBQUNYLGdCQUFnQixFQUFFLENBQUE7QUFDL0IsR0FBQTtBQUVBWSxFQUFBQSxTQUFTQSxHQUFHO0FBQ1IsSUFBQSxJQUFJLENBQUMvQixLQUFLLENBQUNRLE9BQU8sR0FBRyxLQUFLLENBQUE7QUFFMUIsSUFBQSxJQUFJLENBQUN2QixNQUFNLENBQUNXLEdBQUcsQ0FBQ0MsS0FBSyxDQUFDWSxHQUFHLENBQUMsWUFBWSxFQUFFLElBQUksQ0FBQ0osZUFBZSxFQUFFLElBQUksQ0FBQyxDQUFBO0lBQ25FLElBQUksSUFBSSxDQUFDcEIsTUFBTSxDQUFDVyxHQUFHLENBQUNDLEtBQUssQ0FBQ0osTUFBTSxFQUFFO0FBQzlCLE1BQUEsSUFBSSxDQUFDUixNQUFNLENBQUNXLEdBQUcsQ0FBQ0MsS0FBSyxDQUFDSixNQUFNLENBQUNnQixHQUFHLENBQUMsS0FBSyxFQUFFLElBQUksQ0FBQ0MsWUFBWSxFQUFFLElBQUksQ0FBQyxDQUFBO0FBQ2hFLE1BQUEsSUFBSSxDQUFDekIsTUFBTSxDQUFDVyxHQUFHLENBQUNDLEtBQUssQ0FBQ0osTUFBTSxDQUFDZ0IsR0FBRyxDQUFDLFFBQVEsRUFBRSxJQUFJLENBQUNFLGNBQWMsRUFBRSxJQUFJLENBQUMsQ0FBQTtBQUN6RSxLQUFBO0lBRUEsSUFBSSxDQUFDVCxxQkFBcUIsRUFBRSxDQUFBO0FBQ2hDLEdBQUE7QUFFQThCLEVBQUFBLFFBQVFBLEdBQUc7QUFDUDtJQUNBLElBQUksQ0FBQ0QsU0FBUyxFQUFFLENBQUE7O0FBRWhCO0FBQ0EsSUFBQSxJQUFJLENBQUMvQixLQUFLLENBQUNpQyxPQUFPLEVBQUUsQ0FBQTs7QUFFcEI7SUFDQSxJQUFJLENBQUNDLFdBQVcsR0FBRyxJQUFJLENBQUE7QUFDM0IsR0FBQTs7QUFFQTtBQUNKO0FBQ0E7QUFDQTtBQUNBO0VBQ0ksSUFBSUMscUJBQXFCQSxDQUFDQyxNQUFNLEVBQUU7QUFDOUIsSUFBQSxJQUFJLENBQUNwQyxLQUFLLENBQUNtQyxxQkFBcUIsR0FBR0MsTUFBTSxDQUFBO0FBQzdDLEdBQUE7RUFFQSxJQUFJRCxxQkFBcUJBLEdBQUc7QUFDeEIsSUFBQSxPQUFPLElBQUksQ0FBQ25DLEtBQUssQ0FBQ21DLHFCQUFxQixDQUFBO0FBQzNDLEdBQUE7RUFFQSxJQUFJRSxZQUFZQSxDQUFDQyxLQUFLLEVBQUU7QUFDcEIsSUFBQSxJQUFJLENBQUN0QyxLQUFLLENBQUNxQyxZQUFZLEdBQUdDLEtBQUssQ0FBQTtBQUNuQyxHQUFBO0VBRUEsSUFBSUQsWUFBWUEsR0FBRztBQUNmLElBQUEsT0FBTyxJQUFJLENBQUNyQyxLQUFLLENBQUNxQyxZQUFZLENBQUE7QUFDbEMsR0FBQTtBQUNKLENBQUE7QUFFQSxTQUFTRSxlQUFlQSxDQUFDdEIsSUFBSSxFQUFFdUIsWUFBWSxFQUFFQyxPQUFPLEVBQUVDLGVBQWUsRUFBRTtBQUNuRSxFQUFBLE1BQU1DLENBQUMsR0FBRzdELGNBQWMsQ0FBQzhELFNBQVMsQ0FBQTtBQUNsQ2hFLEVBQUFBLFdBQVcsQ0FBQ2lFLElBQUksQ0FBQzVCLElBQUksQ0FBQyxDQUFBO0FBQ3RCcEMsRUFBQUEsa0JBQWtCLENBQUNnRSxJQUFJLENBQUNMLFlBQVksQ0FBQyxDQUFBO0FBRXJDTSxFQUFBQSxNQUFNLENBQUNDLGNBQWMsQ0FBQ0osQ0FBQyxFQUFFMUIsSUFBSSxFQUFFO0lBQzNCK0IsR0FBRyxFQUFFLFlBQVk7QUFDYixNQUFBLE9BQU8sSUFBSSxDQUFDQyxJQUFJLENBQUNoQyxJQUFJLENBQUMsQ0FBQTtLQUN6QjtBQUNEaUMsSUFBQUEsR0FBRyxFQUFFLFVBQVVaLEtBQUssRUFBRTtBQUNsQixNQUFBLE1BQU1XLElBQUksR0FBRyxJQUFJLENBQUNBLElBQUksQ0FBQTtBQUN0QixNQUFBLE1BQU1FLFFBQVEsR0FBR0YsSUFBSSxDQUFDaEMsSUFBSSxDQUFDLENBQUE7QUFDM0IsTUFBQSxJQUFJLENBQUN5QixlQUFlLElBQUlTLFFBQVEsS0FBS2IsS0FBSyxFQUFFLE9BQUE7QUFDNUNXLE1BQUFBLElBQUksQ0FBQ2hDLElBQUksQ0FBQyxHQUFHcUIsS0FBSyxDQUFBO01BQ2xCLElBQUlHLE9BQU8sRUFBRUEsT0FBTyxDQUFDVyxJQUFJLENBQUMsSUFBSSxFQUFFZCxLQUFLLEVBQUVhLFFBQVEsQ0FBQyxDQUFBO0tBQ25EO0FBQ0RFLElBQUFBLFlBQVksRUFBRSxJQUFBO0FBQ2xCLEdBQUMsQ0FBQyxDQUFBO0FBQ04sQ0FBQTtBQUVBLFNBQVNDLFlBQVlBLEdBQUc7RUFDcEJmLGVBQWUsQ0FBQyxTQUFTLEVBQUUsSUFBSSxFQUFFLFVBQVVnQixRQUFRLEVBQUVKLFFBQVEsRUFBRTtJQUMzRCxJQUFJLENBQUNLLFlBQVksQ0FBQyxJQUFJLEVBQUVMLFFBQVEsRUFBRUksUUFBUSxDQUFDLENBQUE7QUFDL0MsR0FBQyxDQUFDLENBQUE7QUFDRmhCLEVBQUFBLGVBQWUsQ0FBQyxPQUFPLEVBQUUsSUFBSSxDQUFDLENBQUE7RUFDOUJBLGVBQWUsQ0FBQyxNQUFNLEVBQUUsYUFBYSxFQUFFLFVBQVVnQixRQUFRLEVBQUVKLFFBQVEsRUFBRTtJQUNqRSxJQUFJLENBQUNsRSxNQUFNLENBQUN3RSxVQUFVLENBQUMsSUFBSSxFQUFFTixRQUFRLEVBQUVJLFFBQVEsQ0FBQyxDQUFBO0FBQ2hEO0FBQ0E7SUFDQSxJQUFJLENBQUN2QyxpQkFBaUIsRUFBRSxDQUFBO0FBQzVCLEdBQUMsQ0FBQyxDQUFBO0FBQ0Z1QixFQUFBQSxlQUFlLENBQUMsT0FBTyxFQUFFLElBQUltQixLQUFLLENBQUMsQ0FBQyxFQUFFLENBQUMsRUFBRSxDQUFDLENBQUMsRUFBRSxVQUFVSCxRQUFRLEVBQUVKLFFBQVEsRUFBRTtBQUN2RSxJQUFBLElBQUksQ0FBQ25ELEtBQUssQ0FBQzJELFFBQVEsQ0FBQ0osUUFBUSxDQUFDLENBQUE7R0FDaEMsRUFBRSxJQUFJLENBQUMsQ0FBQTtFQUNSaEIsZUFBZSxDQUFDLFdBQVcsRUFBRSxDQUFDLEVBQUUsVUFBVWdCLFFBQVEsRUFBRUosUUFBUSxFQUFFO0FBQzFELElBQUEsSUFBSSxDQUFDbkQsS0FBSyxDQUFDNEQsU0FBUyxHQUFHTCxRQUFRLENBQUE7QUFDbkMsR0FBQyxDQUFDLENBQUE7RUFDRmhCLGVBQWUsQ0FBQyxXQUFXLEVBQUUsQ0FBQyxFQUFFLFVBQVVnQixRQUFRLEVBQUVKLFFBQVEsRUFBRTtBQUMxRCxJQUFBLElBQUksQ0FBQ25ELEtBQUssQ0FBQzZELFNBQVMsR0FBR04sUUFBUSxDQUFBO0FBQ25DLEdBQUMsQ0FBQyxDQUFBO0VBQ0ZoQixlQUFlLENBQUMsT0FBTyxFQUFFdUIsbUJBQW1CLEVBQUUsVUFBVVAsUUFBUSxFQUFFSixRQUFRLEVBQUU7QUFDeEUsSUFBQSxJQUFJLENBQUNuRCxLQUFLLENBQUMrRCxLQUFLLEdBQUdSLFFBQVEsQ0FBQTtBQUMvQixHQUFDLENBQUMsQ0FBQTtFQUNGaEIsZUFBZSxDQUFDLG1CQUFtQixFQUFFLElBQUksRUFBRSxVQUFVZ0IsUUFBUSxFQUFFSixRQUFRLEVBQUU7QUFDckUsSUFBQSxJQUFJLENBQUNuRCxLQUFLLENBQUNnRSxpQkFBaUIsR0FBR1QsUUFBUSxDQUFBO0FBQzNDLEdBQUMsQ0FBQyxDQUFBO0VBQ0ZoQixlQUFlLENBQUMsYUFBYSxFQUFFLEtBQUssRUFBRSxVQUFVZ0IsUUFBUSxFQUFFSixRQUFRLEVBQUU7QUFDaEUsSUFBQSxJQUFJLENBQUNuRCxLQUFLLENBQUNpRSxXQUFXLEdBQUdWLFFBQVEsQ0FBQTtBQUNyQyxHQUFDLENBQUMsQ0FBQTtFQUNGaEIsZUFBZSxDQUFDLGdCQUFnQixFQUFFLEVBQUUsRUFBRSxVQUFVZ0IsUUFBUSxFQUFFSixRQUFRLEVBQUU7QUFDaEUsSUFBQSxJQUFJLENBQUNuRCxLQUFLLENBQUNrRSxjQUFjLEdBQUdYLFFBQVEsQ0FBQTtBQUN4QyxHQUFDLENBQUMsQ0FBQTtFQUNGaEIsZUFBZSxDQUFDLGlCQUFpQixFQUFFLENBQUMsRUFBRSxVQUFVZ0IsUUFBUSxFQUFFSixRQUFRLEVBQUU7QUFDaEUsSUFBQSxJQUFJLENBQUNuRCxLQUFLLENBQUNtRSxlQUFlLEdBQUdaLFFBQVEsQ0FBQTtBQUN6QyxHQUFDLENBQUMsQ0FBQTtFQUNGaEIsZUFBZSxDQUFDLGtCQUFrQixFQUFFLElBQUksRUFBRSxVQUFVZ0IsUUFBUSxFQUFFSixRQUFRLEVBQUU7QUFDcEUsSUFBQSxJQUFJLENBQUNuRCxLQUFLLENBQUNvRSxnQkFBZ0IsR0FBR2IsUUFBUSxDQUFBO0FBQzFDLEdBQUMsQ0FBQyxDQUFBO0VBQ0ZoQixlQUFlLENBQUMsWUFBWSxFQUFFLElBQUksRUFBRSxVQUFVZ0IsUUFBUSxFQUFFSixRQUFRLEVBQUU7QUFDOUQsSUFBQSxJQUFJLENBQUNuRCxLQUFLLENBQUNxRSxVQUFVLEdBQUcsQ0FBQyxJQUFJLEdBQUdDLElBQUksQ0FBQ0MsS0FBSyxDQUFDaEIsUUFBUSxFQUFFLENBQUMsRUFBRSxDQUFDLENBQUMsQ0FBQTtBQUM5RCxHQUFDLENBQUMsQ0FBQTtFQUNGaEIsZUFBZSxDQUFDLGFBQWEsRUFBRSxDQUFDLEVBQUUsVUFBVWdCLFFBQVEsRUFBRUosUUFBUSxFQUFFO0FBQzVELElBQUEsSUFBSSxDQUFDbkQsS0FBSyxDQUFDd0UsV0FBVyxHQUFHRixJQUFJLENBQUNDLEtBQUssQ0FBQ0UsSUFBSSxDQUFDQyxLQUFLLENBQUNuQixRQUFRLENBQUMsRUFBRSxDQUFDLEVBQUUsQ0FBQyxDQUFDLENBQUE7QUFDbkUsR0FBQyxDQUFDLENBQUE7RUFDRmhCLGVBQWUsQ0FBQyxnQkFBZ0IsRUFBRSxDQUFDLEVBQUUsVUFBVWdCLFFBQVEsRUFBRUosUUFBUSxFQUFFO0FBQy9ELElBQUEsSUFBSSxDQUFDbkQsS0FBSyxDQUFDMkUsY0FBYyxHQUFHTCxJQUFJLENBQUNDLEtBQUssQ0FBQ0UsSUFBSSxDQUFDQyxLQUFLLENBQUNuQixRQUFRLENBQUMsRUFBRSxDQUFDLEVBQUUsR0FBRyxDQUFDLENBQUE7QUFDeEUsR0FBQyxDQUFDLENBQUE7RUFDRmhCLGVBQWUsQ0FBQyxVQUFVLEVBQUUsQ0FBQyxFQUFFLFVBQVVnQixRQUFRLEVBQUVKLFFBQVEsRUFBRTtBQUN6RCxJQUFBLElBQUksQ0FBQ25ELEtBQUssQ0FBQzRFLFFBQVEsR0FBR04sSUFBSSxDQUFDQyxLQUFLLENBQUNoQixRQUFRLEVBQUUsQ0FBQyxFQUFFLEdBQUcsQ0FBQyxDQUFBO0FBQ3RELEdBQUMsQ0FBQyxDQUFBO0VBQ0ZoQixlQUFlLENBQUMscUJBQXFCLEVBQUUsR0FBRyxFQUFFLFVBQVVnQixRQUFRLEVBQUVKLFFBQVEsRUFBRTtBQUN0RSxJQUFBLElBQUksQ0FBQ25ELEtBQUssQ0FBQzZFLG1CQUFtQixHQUFHUCxJQUFJLENBQUNDLEtBQUssQ0FBQ2hCLFFBQVEsRUFBRSxDQUFDLEVBQUUsQ0FBQyxDQUFDLENBQUE7QUFDL0QsR0FBQyxDQUFDLENBQUE7RUFDRmhCLGVBQWUsQ0FBQyxrQkFBa0IsRUFBRSxDQUFDLEVBQUUsVUFBVWdCLFFBQVEsRUFBRUosUUFBUSxFQUFFO0FBQ2pFLElBQUEsSUFBSSxDQUFDbkQsS0FBSyxDQUFDOEUsZ0JBQWdCLEdBQUdSLElBQUksQ0FBQ0MsS0FBSyxDQUFDaEIsUUFBUSxFQUFFLENBQUMsRUFBRSxDQUFDLENBQUMsQ0FBQTtBQUM1RCxHQUFDLENBQUMsQ0FBQTtFQUNGaEIsZUFBZSxDQUFDLE9BQU8sRUFBRSxFQUFFLEVBQUUsVUFBVWdCLFFBQVEsRUFBRUosUUFBUSxFQUFFO0FBQ3ZELElBQUEsSUFBSSxDQUFDbkQsS0FBSyxDQUFDK0UsY0FBYyxHQUFHeEIsUUFBUSxDQUFBO0FBQ3hDLEdBQUMsQ0FBQyxDQUFBO0VBQ0ZoQixlQUFlLENBQUMsZ0JBQWdCLEVBQUUsRUFBRSxFQUFFLFVBQVVnQixRQUFRLEVBQUVKLFFBQVEsRUFBRTtBQUNoRSxJQUFBLElBQUksQ0FBQ25ELEtBQUssQ0FBQ2dGLGNBQWMsR0FBR3pCLFFBQVEsQ0FBQTtBQUN4QyxHQUFDLENBQUMsQ0FBQTtFQUNGaEIsZUFBZSxDQUFDLGdCQUFnQixFQUFFLEVBQUUsRUFBRSxVQUFVZ0IsUUFBUSxFQUFFSixRQUFRLEVBQUU7QUFDaEUsSUFBQSxJQUFJLENBQUNuRCxLQUFLLENBQUNpRixjQUFjLEdBQUcxQixRQUFRLENBQUE7QUFDeEMsR0FBQyxDQUFDLENBQUE7RUFDRmhCLGVBQWUsQ0FBQyxhQUFhLEVBQUUyQyxtQkFBbUIsRUFBRSxVQUFVM0IsUUFBUSxFQUFFSixRQUFRLEVBQUU7QUFDOUUsSUFBQSxJQUFJLENBQUNuRCxLQUFLLENBQUNtRixXQUFXLEdBQUc1QixRQUFRLENBQUE7QUFDckMsR0FBQyxDQUFDLENBQUE7RUFDRmhCLGVBQWUsQ0FBQyxZQUFZLEVBQUU2QyxXQUFXLEVBQUUsVUFBVTdCLFFBQVEsRUFBRUosUUFBUSxFQUFFO0FBQ3JFLElBQUEsSUFBSSxDQUFDbkQsS0FBSyxDQUFDcUYsVUFBVSxHQUFHOUIsUUFBUSxDQUFBO0FBQ3BDLEdBQUMsQ0FBQyxDQUFBO0VBQ0ZoQixlQUFlLENBQUMsYUFBYSxFQUFFLEVBQUUsRUFBRSxVQUFVZ0IsUUFBUSxFQUFFSixRQUFRLEVBQUU7QUFDN0QsSUFBQSxJQUFJLENBQUNuRCxLQUFLLENBQUNzRixXQUFXLEdBQUcvQixRQUFRLENBQUE7QUFDckMsR0FBQyxDQUFDLENBQUE7RUFDRmhCLGVBQWUsQ0FBQyxhQUFhLEVBQUVnRCxhQUFhLEVBQUUsVUFBVWhDLFFBQVEsRUFBRUosUUFBUSxFQUFFO0FBQ3hFLElBQUEsSUFBSSxDQUFDbkQsS0FBSyxDQUFDd0YsV0FBVyxHQUFHakMsUUFBUSxDQUFBO0FBQ3JDLEdBQUMsQ0FBQyxDQUFBO0VBQ0ZoQixlQUFlLENBQUMsU0FBUyxFQUFFLElBQUksR0FBRyxJQUFJLEVBQUUsVUFBVWdCLFFBQVEsRUFBRUosUUFBUSxFQUFFO0FBQ2xFLElBQUEsSUFBSSxDQUFDbkQsS0FBSyxDQUFDeUYsT0FBTyxHQUFHbkIsSUFBSSxDQUFDQyxLQUFLLENBQUNoQixRQUFRLEVBQUUsQ0FBQyxFQUFFLENBQUMsQ0FBQyxDQUFBO0FBQ25ELEdBQUMsQ0FBQyxDQUFBO0VBQ0ZoQixlQUFlLENBQUMsYUFBYSxFQUFFLElBQUksRUFBRSxVQUFVZ0IsUUFBUSxFQUFFSixRQUFRLEVBQUU7SUFDL0QsSUFBSSxJQUFJLENBQUMvRCxjQUFjLEtBQU1tRSxRQUFRLFlBQVltQyxLQUFLLElBQUluQyxRQUFRLENBQUN4QyxFQUFFLEtBQUssSUFBSSxDQUFDM0IsY0FBYyxJQUFLbUUsUUFBUSxLQUFLLElBQUksQ0FBQ25FLGNBQWMsQ0FBQyxFQUMvSCxPQUFBO0lBRUosSUFBSSxDQUFDeUMsbUJBQW1CLEVBQUUsQ0FBQTtJQUMxQixJQUFJLENBQUN6QyxjQUFjLEdBQUcsSUFBSSxDQUFBO0lBRTFCLElBQUltRSxRQUFRLFlBQVltQyxLQUFLLEVBQUU7QUFDM0IsTUFBQSxJQUFJLENBQUN6QyxJQUFJLENBQUNmLFdBQVcsR0FBR3FCLFFBQVEsQ0FBQ3hDLEVBQUUsQ0FBQTtBQUNuQyxNQUFBLElBQUksQ0FBQzNCLGNBQWMsR0FBR21FLFFBQVEsQ0FBQ3hDLEVBQUUsQ0FBQTtBQUNqQyxNQUFBLElBQUksQ0FBQ1ksZ0JBQWdCLENBQUM0QixRQUFRLENBQUMsQ0FBQTtBQUNuQyxLQUFDLE1BQU0sSUFBSSxPQUFPQSxRQUFRLEtBQUssUUFBUSxFQUFFO01BQ3JDLElBQUksQ0FBQ25FLGNBQWMsR0FBR21FLFFBQVEsQ0FBQTtBQUM5QixNQUFBLE1BQU0zQixLQUFLLEdBQUcsSUFBSSxDQUFDM0MsTUFBTSxDQUFDVyxHQUFHLENBQUM0QixNQUFNLENBQUN3QixHQUFHLENBQUNPLFFBQVEsQ0FBQyxDQUFBO0FBQ2xELE1BQUEsSUFBSTNCLEtBQUssRUFBRTtBQUNQLFFBQUEsSUFBSSxDQUFDRCxnQkFBZ0IsQ0FBQ0MsS0FBSyxDQUFDLENBQUE7QUFDaEMsT0FBQyxNQUFNO1FBQ0gsSUFBSSxDQUFDdkMsZUFBZSxHQUFHLElBQUksQ0FBQTtRQUMzQixJQUFJLENBQUNKLE1BQU0sQ0FBQ1csR0FBRyxDQUFDNEIsTUFBTSxDQUFDWixFQUFFLENBQUMsTUFBTSxHQUFHLElBQUksQ0FBQ3hCLGNBQWMsRUFBRSxJQUFJLENBQUN1QyxnQkFBZ0IsRUFBRSxJQUFJLENBQUMsQ0FBQTtBQUN4RixPQUFBO0FBQ0osS0FBQTtBQUNKLEdBQUMsQ0FBQyxDQUFBO0VBQ0ZZLGVBQWUsQ0FBQyxRQUFRLEVBQUUsSUFBSSxFQUFFLFVBQVVnQixRQUFRLEVBQUVKLFFBQVEsRUFBRTtBQUMxRCxJQUFBLElBQUksQ0FBQ25ELEtBQUssQ0FBQzhCLE1BQU0sR0FBR3lCLFFBQVEsQ0FBQTtBQUNoQyxHQUFDLENBQUMsQ0FBQTtFQUNGaEIsZUFBZSxDQUFDLGlCQUFpQixFQUFFLENBQUMsRUFBRSxVQUFVZ0IsUUFBUSxFQUFFSixRQUFRLEVBQUU7QUFDaEUsSUFBQSxJQUFJLENBQUNuRCxLQUFLLENBQUMyRixlQUFlLEdBQUdyQixJQUFJLENBQUNDLEtBQUssQ0FBQ2hCLFFBQVEsRUFBRSxDQUFDLEVBQUUsQ0FBQyxDQUFDLENBQUE7QUFDM0QsR0FBQyxDQUFDLENBQUE7RUFDRmhCLGVBQWUsQ0FBQyxlQUFlLEVBQUUsSUFBSSxFQUFFLFVBQVVnQixRQUFRLEVBQUVKLFFBQVEsRUFBRTtBQUNqRSxJQUFBLElBQUksQ0FBQ25ELEtBQUssQ0FBQzRGLGFBQWEsR0FBR3JDLFFBQVEsQ0FBQTtBQUN2QyxHQUFDLENBQUMsQ0FBQTtFQUNGaEIsZUFBZSxDQUFDLGVBQWUsRUFBRSxLQUFLLEVBQUUsVUFBVWdCLFFBQVEsRUFBRUosUUFBUSxFQUFFO0FBQ2xFLElBQUEsSUFBSSxDQUFDbkQsS0FBSyxDQUFDNkYsYUFBYSxHQUFHdEMsUUFBUSxDQUFBO0FBQ3ZDLEdBQUMsQ0FBQyxDQUFBO0VBQ0ZoQixlQUFlLENBQUMsYUFBYSxFQUFFLENBQUMsRUFBRSxVQUFVZ0IsUUFBUSxFQUFFSixRQUFRLEVBQUU7SUFDNUQsSUFBSUksUUFBUSxLQUFLLENBQUMsSUFBSSxJQUFJLENBQUN1QyxXQUFXLEtBQUssSUFBSSxFQUFFO0FBQzdDLE1BQUEsSUFBSSxDQUFDLElBQUksQ0FBQ3hHLGFBQWEsRUFBRSxJQUFJLENBQUNBLGFBQWEsR0FBRyxJQUFJeUcsSUFBSSxFQUFFLENBQUE7TUFDeEQsSUFBSUMsR0FBRyxHQUFHLENBQUMsQ0FBQTtNQUNYLElBQUlDLEdBQUcsR0FBRyxDQUFDLENBQUE7TUFDWCxJQUFJLElBQUksQ0FBQ0gsV0FBVyxFQUFFO0FBQ2xCRSxRQUFBQSxHQUFHLEdBQUcsSUFBSSxDQUFDRixXQUFXLENBQUNJLENBQUMsQ0FBQTtBQUN4QkQsUUFBQUEsR0FBRyxHQUFHLElBQUksQ0FBQ0gsV0FBVyxDQUFDSyxDQUFDLENBQUE7QUFDNUIsT0FBQTtNQUNBLE1BQU14RCxDQUFDLEdBQUc4QixJQUFJLENBQUMyQixHQUFHLENBQUM3QyxRQUFRLEdBQUdlLElBQUksQ0FBQytCLFVBQVUsQ0FBQyxDQUFBO01BQzlDLE1BQU1DLENBQUMsR0FBRzdCLElBQUksQ0FBQzhCLEdBQUcsQ0FBQ2hELFFBQVEsR0FBR2UsSUFBSSxDQUFDK0IsVUFBVSxDQUFDLENBQUE7TUFDOUMsSUFBSSxDQUFDL0csYUFBYSxDQUFDNEQsR0FBRyxDQUFDUCxDQUFDLEdBQUdxRCxHQUFHLEVBQUUsQ0FBQ00sQ0FBQyxHQUFHTixHQUFHLEVBQUVNLENBQUMsR0FBR0wsR0FBRyxFQUFFdEQsQ0FBQyxHQUFHc0QsR0FBRyxDQUFDLENBQUE7QUFDM0QsTUFBQSxJQUFJLENBQUNqRyxLQUFLLENBQUN3RyxlQUFlLEdBQUcsSUFBSSxDQUFDbEgsYUFBYSxDQUFBO0FBQ25ELEtBQUMsTUFBTTtBQUNILE1BQUEsSUFBSSxDQUFDVSxLQUFLLENBQUN3RyxlQUFlLEdBQUcsSUFBSSxDQUFBO0FBQ3JDLEtBQUE7QUFDSixHQUFDLENBQUMsQ0FBQTtFQUNGakUsZUFBZSxDQUFDLGFBQWEsRUFBRSxJQUFJLEVBQUUsVUFBVWdCLFFBQVEsRUFBRUosUUFBUSxFQUFFO0lBQy9ELElBQUlJLFFBQVEsS0FBSyxJQUFJLElBQUksSUFBSSxDQUFDa0QsV0FBVyxLQUFLLENBQUMsRUFBRTtBQUM3QyxNQUFBLElBQUksQ0FBQyxJQUFJLENBQUNuSCxhQUFhLEVBQUUsSUFBSSxDQUFDQSxhQUFhLEdBQUcsSUFBSXlHLElBQUksRUFBRSxDQUFBO0FBQ3hELE1BQUEsTUFBTUMsR0FBRyxHQUFHekMsUUFBUSxDQUFDMkMsQ0FBQyxDQUFBO0FBQ3RCLE1BQUEsTUFBTUQsR0FBRyxHQUFHMUMsUUFBUSxDQUFDNEMsQ0FBQyxDQUFBO0FBQ3RCLE1BQUEsTUFBTXhELENBQUMsR0FBRzhCLElBQUksQ0FBQzJCLEdBQUcsQ0FBQyxJQUFJLENBQUNLLFdBQVcsR0FBR25DLElBQUksQ0FBQytCLFVBQVUsQ0FBQyxDQUFBO0FBQ3RELE1BQUEsTUFBTUMsQ0FBQyxHQUFHN0IsSUFBSSxDQUFDOEIsR0FBRyxDQUFDLElBQUksQ0FBQ0UsV0FBVyxHQUFHbkMsSUFBSSxDQUFDK0IsVUFBVSxDQUFDLENBQUE7TUFDdEQsSUFBSSxDQUFDL0csYUFBYSxDQUFDNEQsR0FBRyxDQUFDUCxDQUFDLEdBQUdxRCxHQUFHLEVBQUUsQ0FBQ00sQ0FBQyxHQUFHTixHQUFHLEVBQUVNLENBQUMsR0FBR0wsR0FBRyxFQUFFdEQsQ0FBQyxHQUFHc0QsR0FBRyxDQUFDLENBQUE7QUFDM0QsTUFBQSxJQUFJLENBQUNqRyxLQUFLLENBQUN3RyxlQUFlLEdBQUcsSUFBSSxDQUFDbEgsYUFBYSxDQUFBO0FBQ25ELEtBQUMsTUFBTTtBQUNILE1BQUEsSUFBSSxDQUFDVSxLQUFLLENBQUN3RyxlQUFlLEdBQUcsSUFBSSxDQUFBO0FBQ3JDLEtBQUE7R0FDSCxFQUFFLElBQUksQ0FBQyxDQUFBO0VBQ1JqRSxlQUFlLENBQUMsY0FBYyxFQUFFLElBQUksRUFBRSxVQUFVZ0IsUUFBUSxFQUFFSixRQUFRLEVBQUU7QUFDaEUsSUFBQSxJQUFJLENBQUNuRCxLQUFLLENBQUMwRyxZQUFZLEdBQUduRCxRQUFRLENBQUE7R0FDckMsRUFBRSxJQUFJLENBQUMsQ0FBQTtFQUNSaEIsZUFBZSxDQUFDLGtCQUFrQixFQUFFb0UscUJBQXFCLEVBQUUsVUFBVXBELFFBQVEsRUFBRUosUUFBUSxFQUFFO0FBQ3JGLElBQUEsSUFBSSxDQUFDbkQsS0FBSyxDQUFDNEcsZ0JBQWdCLEdBQUdyRCxRQUFRLENBQUE7R0FDekMsRUFBRSxJQUFJLENBQUMsQ0FBQTtFQUNSaEIsZUFBZSxDQUFDLE1BQU0sRUFBRSxDQUFDLEVBQUUsVUFBVWdCLFFBQVEsRUFBRUosUUFBUSxFQUFFO0FBQ3JELElBQUEsSUFBSSxDQUFDbkQsS0FBSyxDQUFDNkcsSUFBSSxHQUFHdEQsUUFBUSxDQUFBO0FBQzlCLEdBQUMsQ0FBQyxDQUFBO0VBQ0ZoQixlQUFlLENBQUMsZUFBZSxFQUFFLElBQUksRUFBRSxVQUFVZ0IsUUFBUSxFQUFFSixRQUFRLEVBQUU7QUFDakUsSUFBQSxJQUFJSSxRQUFRLEVBQUU7QUFDVixNQUFBLElBQUksQ0FBQ3ZELEtBQUssQ0FBQzZHLElBQUksSUFBSUMsbUJBQW1CLENBQUE7QUFDMUMsS0FBQyxNQUFNO0FBQ0gsTUFBQSxJQUFJLENBQUM5RyxLQUFLLENBQUM2RyxJQUFJLElBQUksQ0FBQ0MsbUJBQW1CLENBQUE7QUFDM0MsS0FBQTtBQUNBLElBQUEsSUFBSSxDQUFDOUcsS0FBSyxDQUFDK0csV0FBVyxFQUFFLENBQUE7QUFDNUIsR0FBQyxDQUFDLENBQUE7RUFDRnhFLGVBQWUsQ0FBQyxtQkFBbUIsRUFBRSxLQUFLLEVBQUUsVUFBVWdCLFFBQVEsRUFBRUosUUFBUSxFQUFFO0FBQ3RFLElBQUEsSUFBSUksUUFBUSxFQUFFO0FBQ1YsTUFBQSxJQUFJLENBQUN2RCxLQUFLLENBQUM2RyxJQUFJLElBQUlHLHVCQUF1QixDQUFBO01BQzFDLElBQUksSUFBSSxDQUFDQyxJQUFJLEVBQUUsSUFBSSxDQUFDakgsS0FBSyxDQUFDNkcsSUFBSSxJQUFJLENBQUNLLFNBQVMsQ0FBQTtBQUNoRCxLQUFDLE1BQU07QUFDSCxNQUFBLElBQUksQ0FBQ2xILEtBQUssQ0FBQzZHLElBQUksSUFBSSxDQUFDRyx1QkFBdUIsQ0FBQTtNQUMzQyxJQUFJLElBQUksQ0FBQ0MsSUFBSSxFQUFFLElBQUksQ0FBQ2pILEtBQUssQ0FBQzZHLElBQUksSUFBSUssU0FBUyxDQUFBO0FBQy9DLEtBQUE7QUFDSixHQUFDLENBQUMsQ0FBQTtFQUNGM0UsZUFBZSxDQUFDLE1BQU0sRUFBRSxLQUFLLEVBQUUsVUFBVWdCLFFBQVEsRUFBRUosUUFBUSxFQUFFO0FBQ3pELElBQUEsSUFBSUksUUFBUSxFQUFFO0FBQ1YsTUFBQSxJQUFJLENBQUN2RCxLQUFLLENBQUM2RyxJQUFJLElBQUlLLFNBQVMsQ0FBQTtNQUM1QixJQUFJLElBQUksQ0FBQ0MsaUJBQWlCLEVBQUUsSUFBSSxDQUFDbkgsS0FBSyxDQUFDNkcsSUFBSSxJQUFJLENBQUNHLHVCQUF1QixDQUFBO0FBQzNFLEtBQUMsTUFBTTtBQUNILE1BQUEsSUFBSSxDQUFDaEgsS0FBSyxDQUFDNkcsSUFBSSxJQUFJLENBQUNLLFNBQVMsQ0FBQTtNQUM3QixJQUFJLElBQUksQ0FBQ0MsaUJBQWlCLEVBQUUsSUFBSSxDQUFDbkgsS0FBSyxDQUFDNkcsSUFBSSxJQUFJRyx1QkFBdUIsQ0FBQTtBQUMxRSxLQUFBO0FBQ0EsSUFBQSxJQUFJLENBQUNoSCxLQUFLLENBQUMrRyxXQUFXLEVBQUUsQ0FBQTtBQUM1QixHQUFDLENBQUMsQ0FBQTtFQUNGeEUsZUFBZSxDQUFDLFNBQVMsRUFBRSxJQUFJLEVBQUUsVUFBVWdCLFFBQVEsRUFBRUosUUFBUSxFQUFFO0FBQzNELElBQUEsSUFBSSxDQUFDbkQsS0FBSyxDQUFDb0gsT0FBTyxHQUFHN0QsUUFBUSxDQUFBO0FBQ2pDLEdBQUMsQ0FBQyxDQUFBO0VBQ0ZoQixlQUFlLENBQUMsVUFBVSxFQUFFLEtBQUssRUFBRSxVQUFVZ0IsUUFBUSxFQUFFSixRQUFRLEVBQUU7QUFDN0QsSUFBQSxJQUFJLENBQUNuRCxLQUFLLENBQUNxSCxRQUFRLEdBQUc5RCxRQUFRLENBQUE7QUFDbEMsR0FBQyxDQUFDLENBQUE7RUFDRmhCLGVBQWUsQ0FBQyxRQUFRLEVBQUUsQ0FBQytFLGFBQWEsQ0FBQyxFQUFFLFVBQVUvRCxRQUFRLEVBQUVKLFFBQVEsRUFBRTtBQUNyRSxJQUFBLEtBQUssSUFBSTNELENBQUMsR0FBRyxDQUFDLEVBQUVBLENBQUMsR0FBRzJELFFBQVEsQ0FBQ3pELE1BQU0sRUFBRUYsQ0FBQyxFQUFFLEVBQUU7QUFDdEMsTUFBQSxNQUFNRyxLQUFLLEdBQUcsSUFBSSxDQUFDVixNQUFNLENBQUNXLEdBQUcsQ0FBQ0MsS0FBSyxDQUFDSixNQUFNLENBQUNLLFlBQVksQ0FBQ3FELFFBQVEsQ0FBQzNELENBQUMsQ0FBQyxDQUFDLENBQUE7TUFDcEUsSUFBSSxDQUFDRyxLQUFLLEVBQUUsU0FBQTtBQUNaQSxNQUFBQSxLQUFLLENBQUNRLFdBQVcsQ0FBQyxJQUFJLENBQUMsQ0FBQTtBQUN2QixNQUFBLElBQUksQ0FBQ0gsS0FBSyxDQUFDSSxXQUFXLENBQUNULEtBQUssQ0FBQyxDQUFBO0FBQ2pDLEtBQUE7QUFDQSxJQUFBLEtBQUssSUFBSUgsQ0FBQyxHQUFHLENBQUMsRUFBRUEsQ0FBQyxHQUFHK0QsUUFBUSxDQUFDN0QsTUFBTSxFQUFFRixDQUFDLEVBQUUsRUFBRTtBQUN0QyxNQUFBLE1BQU1HLEtBQUssR0FBRyxJQUFJLENBQUNWLE1BQU0sQ0FBQ1csR0FBRyxDQUFDQyxLQUFLLENBQUNKLE1BQU0sQ0FBQ0ssWUFBWSxDQUFDeUQsUUFBUSxDQUFDL0QsQ0FBQyxDQUFDLENBQUMsQ0FBQTtNQUNwRSxJQUFJLENBQUNHLEtBQUssRUFBRSxTQUFBO01BQ1osSUFBSSxJQUFJLENBQUNhLE9BQU8sSUFBSSxJQUFJLENBQUN0QixNQUFNLENBQUNzQixPQUFPLEVBQUU7QUFDckNiLFFBQUFBLEtBQUssQ0FBQ0ksUUFBUSxDQUFDLElBQUksQ0FBQyxDQUFBO0FBQ3BCLFFBQUEsSUFBSSxDQUFDQyxLQUFLLENBQUNDLFFBQVEsQ0FBQ04sS0FBSyxDQUFDLENBQUE7QUFDOUIsT0FBQTtBQUNKLEtBQUE7QUFDSixHQUFDLENBQUMsQ0FBQTtBQUVGZixFQUFBQSxXQUFXLENBQUNpRSxJQUFJLENBQUMsY0FBYyxDQUFDLENBQUE7QUFDaENoRSxFQUFBQSxrQkFBa0IsQ0FBQ2dFLElBQUksQ0FBQyxDQUFDLENBQUMsQ0FBQTtBQUM5QixDQUFBO0FBRUFTLFlBQVksRUFBRTs7OzsifQ==
